In [ ]:
def get_listings(api_key, listing_url):
    url = "https://app.scrapeak.com/v1/scrapers/zillow/listing"

    querystring = {
        "api_key": api_key,
        "url":listing_url
    }

    return requests.request("GET", url, params=querystring)

def get_property_detail(api_key, zpid):
    url = "https://app.scrapeak.com/v1/scrapers/zillow/property"

    querystring = {
        "api_key": api_key,
        "zpid":zpid
    }

    return requests.request("GET", url, params=querystring)

def get_zpid(api_key, street, city, state, zip_code=None):
    url = "https://app.scrapeak.com/v1/scrapers/zillow/zpidByAddress"

    querystring = {
        "api_key": api_key,
        "street": street,
        "city": city,
        "state": state,
        "zip_code":zip_code
    }

    return requests.request("GET", url, params=querystring)

# Zillow Property Search
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1afLUQVYLIhv0vDB-GNuYgxfZrJhTzSM5?usp=sharing)

## Overview
| Detail Tag            | Information                                                                                        |
|-----------------------|----------------------------------------------------------------------------------------------------|
| Originally Created By | Ariel Herrera arielherrera@analyticsariel.com |
| External References   | API |
| Input Datasets        | Source name |
| Output Datasets       | Source name |
| Input Data Source     | Pandas DataFrame |
| Output Data Source    | Pandas DataFrame |

## History
| Date         | Developed By  | Reason                                                |
|--------------|---------------|-------------------------------------------------------|
| 22nd Jan 2022 | Ariel Herrera | Create notebook. |

## Getting Started
1. Copy this notebook -> File -> Save a Copy in Drive
2. Directions

## Useful Resources
- [Google Colab Cheat Sheet](https://towardsdatascience.com/cheat-sheet-for-google-colab-63853778c093)

## <font color="blue">Install Packages</font>

## <font color="blue">Imports</font>

In [ ]:
from google.colab import output, drive, files # specific to Google Colab
import pandas as pd
import numpy as np
import plotly.express as px
import requests
import warnings

# settings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)

## <font color="blue">Functions</font>

In [ ]:
def get_listings(api_key, listing_url):
    url = "https://app.scrapeak.com/v1/scrapers/zillow/listing"

    querystring = {
        "api_key": api_key,
        "url":listing_url
    }

    return requests.request("GET", url, params=querystring)

def get_property_detail(api_key, zpid):
    url = "https://app.scrapeak.com/v1/scrapers/zillow/property"

    querystring = {
        "api_key": api_key,
        "zpid":zpid
    }

    return requests.request("GET", url, params=querystring)

def get_zpid(api_key, street, city, state, zip_code=None):
    url = "https://app.scrapeak.com/v1/scrapers/zillow/zpidByAddress"

    querystring = {
        "api_key": api_key,
        "street": street,
        "city": city,
        "state": state,
        "zip_code":zip_code
    }

    return requests.request("GET", url, params=querystring)

## <font color="blue">Locals & Constants</font>

In [ ]:
############
# OPTIONAL #
############

# mount drive
drive.mount("/content/drive", force_remount=False)

# data location
file_dir = "/content/drive/My Drive/Colab Data/input/" # optional

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# read in api key file
# df_api_keys = pd.read_csv(file_dir + "api_keys.csv")

# get keys
api_key = 'e3349076-2e0b-4c7e-81d2-fc0790390649'

## <font color="blue">Data</font>

### <font color="green">1. Property Listings For Sale</font>

In [ ]:
# zillow search url
#listing_url = "https://www.zillow.com/manhattan-new-york-ny/?category=SEMANTIC&searchQueryState=%7B%22isMapVisible%22%3Atrue%2C%22mapBounds%22%3A%7B%22north%22%3A40.877483%2C%22south%22%3A40.683935%2C%22east%22%3A-73.910408%2C%22west%22%3A-74.047237%7D%2C%22usersSearchTerm%22%3A%22Manhattan%20NY%20homes%22%2C%22filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22globalrelevanceex%22%7D%2C%22sche%22%3A%7B%22value%22%3Afalse%7D%2C%22schm%22%3A%7B%22value%22%3Afalse%7D%2C%22schc%22%3A%7B%22value%22%3Afalse%7D%2C%22schu%22%3A%7B%22value%22%3Afalse%7D%2C%22schp%22%3A%7B%22value%22%3Afalse%7D%2C%22schr%22%3A%7B%22value%22%3Afalse%7D%2C%22schh%22%3A%7B%22value%22%3Afalse%7D%7D%2C%22isListVisible%22%3Atrue%2C%22category%22%3A%22cat1%22%2C%22mapZoom%22%3A12%2C%22regionSelection%22%3A%5B%7B%22regionId%22%3A12530%2C%22regionType%22%3A17%7D%5D%7D"
listing_url = 'https://www.zillow.com/chicago-il/?category=SEMANTIC&searchQueryState=%7B%22isMapVisible%22%3Atrue%2C%22mapBounds%22%3A%7B%22north%22%3A42.042916938040854%2C%22south%22%3A41.62442343874204%2C%22east%22%3A-87.33025437792969%2C%22west%22%3A-88.13362962207032%7D%2C%22mapZoom%22%3A11%2C%22usersSearchTerm%22%3A%22Chicago%20IL%20homes%22%2C%22filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22globalrelevanceex%22%7D%2C%22sche%22%3A%7B%22value%22%3Afalse%7D%2C%22schm%22%3A%7B%22value%22%3Afalse%7D%2C%22schh%22%3A%7B%22value%22%3Afalse%7D%2C%22schp%22%3A%7B%22value%22%3Afalse%7D%2C%22schr%22%3A%7B%22value%22%3Afalse%7D%2C%22schc%22%3A%7B%22value%22%3Afalse%7D%2C%22schu%22%3A%7B%22value%22%3Afalse%7D%7D%2C%22isListVisible%22%3Atrue%2C%22regionSelection%22%3A%5B%7B%22regionId%22%3A17426%2C%22regionType%22%3A6%7D%5D%2C%22category%22%3A%22cat1%22%7D'
# get listings
listing_response = get_listings(api_key, listing_url)

In [ ]:
# view all keys
listing_response.json().keys()

dict_keys(['is_success', 'data', 'message', 'info'])

In [ ]:
# check if request is successful
listing_response.json()["is_success"]

True

In [ ]:
listing_response.json()['data']

{'user': {'isLoggedIn': False,
  'hasHousingConnectorPermission': False,
  'savedHomesCount': 0,
  'personalizedSearchTraceID': '693777e0000000000c241b035121d461',
  'guid': 'd1bb6194-19b4-4f03-97fc-62958721ba5e',
  'zuid': '',
  'isBot': False,
  'email': '',
  'displayName': '',
  'isAgent': False,
  'phoneNumber': ''},
 'mapState': {'customRegionPolygonWkt': None,
  'schoolPolygonWkt': None,
  'isCurrentLocationSearch': False,
  'userPosition': {'lat': None, 'lon': None}},
 'regionState': {'regionInfo': [{'regionId': 17426,
    'regionType': 6,
    'regionName': 'Chicago',
    'displayName': 'Chicago IL',
    'isPointRegion': False}],
  'regionBounds': {'north': 42.02313,
   'south': 41.644334,
   'east': -87.52364,
   'west': -87.940244}},
 'searchPageSeoObject': {'baseUrl': '/chicago-il/',
  'windowTitle': 'Chicago IL Real Estate - Chicago IL Homes For Sale | Zillow',
  'metaDescription': 'Zillow has 5365 homes for sale in Chicago IL. View listing photos, review sales history, and use our detailed real estate filters to find the perfect place.'},
 'requestId': 9,
 'cat1': {'searchResults': {'listResults': [{'zpid': '65548280',
     'palsId': '17001_12521575',
     'id': '65548280',
     'rawHomeStatusCd': 'ForSale',
     'marketingStatusSimplifiedCd': 'For Sale by Agent',
     'imgSrc': 'https://photos.zillowstatic.com/fp/acb5ca10a69ef74fe3fd944d2e04e28c-p_e.jpg',
     'hasImage': True,
     'detailUrl': 'https://www.zillow.com/homedetails/1801-W-Addison-St-APT-1E-Chicago-IL-60613/65548280_zpid/',
     'statusType': 'FOR_SALE',
     'statusText': 'New',
     'countryCurrency': '$',
     'price': '$475,000',
     'unformattedPrice': 475000,
     'address': '1801 W Addison St APT 1E, Chicago, IL 60613',
     'addressStreet': '1801 W Addison St APT 1E',
     'addressCity': 'Chicago',
     'addressState': 'IL',
     'addressZipcode': '60613',
     'isUndisclosedAddress': False,
     'shouldShowRequestOnPrice': False,
     'beds': 2,
     'baths': 2.0,
     'area': 1350,
     'latLong': {'latitude': 41.946644, 'longitude': -87.674385},
     'isZillowOwned': False,
     'flexFieldText': 'Showcase',
     'contentType': 'showcase',
     'hdpData': {'homeInfo': {'zpid': 65548280,
       'streetAddress': '1801 W Addison St APT 1E',
       'zipcode': '60613',
       'city': 'Chicago',
       'state': 'IL',
       'latitude': 41.946644,
       'longitude': -87.674385,
       'price': 475000.0,
       'bathrooms': 2.0,
       'bedrooms': 2.0,
       'livingArea': 1350.0,
       'homeType': 'CONDO',
       'homeStatus': 'FOR_SALE',
       'daysOnZillow': 5,
       'isFeatured': False,
       'shouldHighlight': False,
       'listing_sub_type': {'is_FSBA': True},
       'isUnmappable': False,
       'isPreforeclosureAuction': False,
       'homeStatusForHDP': 'FOR_SALE',
       'priceForHDP': 475000.0,
       'timeOnZillow': 446454000,
       'isNonOwnerOccupied': True,
       'isPremierBuilder': False,
       'isZillowOwned': False,
       'currency': 'USD',
       'country': 'USA',
       'taxAssessedValue': 402920.0,
       'unit': 'Apt 1E',
       'isShowcaseListing': True}},
     'isSaved': False,
     'isUserClaimingOwner': False,
     'isUserConfirmedClaim': False,
     'pgapt': 'ForSale',
     'sgapt': 'For Sale (Broker)',
     'shouldShowZestimateAsPrice': False,
     'has3DModel': True,
     'hasVideo': False,
     'isHomeRec': False,
     'hasAdditionalAttributions': True,
     'isFeaturedListing': False,
     'isShowcaseListing': True,
     'list': True,
     'relaxed': False,
     'brokerName': 'Compass',
     'carouselPhotosComposable': {'baseUrl': 'https://photos.zillowstatic.com/fp/{photoKey}-p_e.jpg',
      'communityBaseUrl': None,
      'photoData': [{'photoKey': 'acb5ca10a69ef74fe3fd944d2e04e28c'},
       {'photoKey': 'd1560b899929c344363193ec9c45c957'},
       {'photoKey': '70fffbdfcee24bf88f92746b1732ec74'},
       {'photoKey': 'bbe360e68599e76fdb912ccacd75e116'},
       {'photoKey': '6cafb7bcec8c5f46126633c13fc6da02'},
       {'photoKey': 'b097ff9efe67044a5faf7475c1d4e0c9'},
       {'photoKey': '6806436a398872648afd35b5267d917b'},
       {'photoKey': 'f36b1ea72b96ff7865037dd5f43202d2'},
       {'photoKey': '979cc950f11647cb998a858068c02f32'},
       {'photoKey': '06c4fb1d60aeb80c65711345dd3b015c'},
       {'photoKey': '89b607cd861ed9b05c711a3f58432ab6'},
       {'photoKey': '306d12b481e2991f334895d14226437b'},
       {'photoKey': '4c1861b81f9b4bcf744d96aeabc90be5'},
       {'photoKey': '8539f651990f61901a53aea0d559282a'},
       {'photoKey': '44c7d1a55bc3252603c9f77b595b3766'},
       {'photoKey': '085a9d2cc9ef2099370a95c774cf4acb'},
       {'photoKey': 'a4eee1346721f4380bc87dfe76eb81fb'},
       {'photoKey': 'f26d31a97ef8b86901cc5d66b0d9536c'},
       {'photoKey': '8802578d07d138d7dd3812b676999aa1'},
       {'photoKey': '6eba411d6c3db4a59a13738861ba4555'},
       {'photoKey': 'b62a1cfa0c62c36ca093104120f53d0f'},
       {'photoKey': 'd1e067660ba217b71dd499cb2aa359ae'}],
      'communityPhotoData': None,
      'isStaticUrls': False},
     'isPaidBuilderNewConstruction': False},
    {'zpid': '441111929',
     'palsId': '17001_12518189',
     'id': '441111929',
     'rawHomeStatusCd': 'ForSale',
     'marketingStatusSimplifiedCd': 'For Sale by Agent',
     'imgSrc': 'https://photos.zillowstatic.com/fp/fee61d003178d968d58301b4a2249945-p_e.jpg',
     'hasImage': True,
     'detailUrl': 'https://www.zillow.com/homedetails/3057-E-79th-Pl-Chicago-IL-60617/441111929_zpid/',
     'statusType': 'FOR_SALE',
     'statusText': 'New',
     'countryCurrency': '$',
     'price': '$149,900',
     'unformattedPrice': 149900,
     'address': '3057 E 79th Pl, Chicago, IL 60617',
     'addressStreet': '3057 E 79th Pl',
     'addressCity': 'Chicago',
     'addressState': 'IL',
     'addressZipcode': '60617',
     'isUndisclosedAddress': False,
     'shouldShowRequestOnPrice': False,
     'beds': 8,
     'baths': 4.0,
     'latLong': {'latitude': 41.7508, 'longitude': -87.54944},
     'isZillowOwned': False,
     'flexFieldText': 'Showcase',
     'contentType': 'showcase',
     'hdpData': {'homeInfo': {'zpid': 441111929,
       'streetAddress': '3057 E 79th Pl',
       'zipcode': '60617',
       'city': 'Chicago',
       'state': 'IL',
       'latitude': 41.7508,
       'longitude': -87.54944,
       'price': 149900.0,
       'bathrooms': 4.0,
       'bedrooms': 8.0,
       'homeType': 'MULTI_FAMILY',
       'homeStatus': 'FOR_SALE',
       'daysOnZillow': 4,
       'isFeatured': False,
       'shouldHighlight': False,
       'listing_sub_type': {'is_FSBA': True},
       'isUnmappable': False,
       'isPreforeclosureAuction': False,
       'homeStatusForHDP': 'FOR_SALE',
       'priceForHDP': 149900.0,
       'timeOnZillow': 363364000,
       'isNonOwnerOccupied': True,
       'isPremierBuilder': False,
       'isZillowOwned': False,
       'currency': 'USD',
       'country': 'USA',
       'taxAssessedValue': 130000.0,
       'lotAreaValue': 4125.0,
       'lotAreaUnit': 'sqft',
       'isShowcaseListing': True}},
     'isSaved': False,
     'isUserClaimingOwner': False,
     'isUserConfirmedClaim': False,
     'pgapt': 'ForSale',
     'sgapt': 'For Sale (Broker)',
     'shouldShowZestimateAsPrice': False,
     'has3DModel': True,
     'hasVideo': False,
     'isHomeRec': False,
     'hasAdditionalAttributions': True,
     'isFeaturedListing': False,
     'isShowcaseListing': True,
     'list': True,
     'relaxed': False,
     'brokerName': 'Redfin Corporation',
     'carouselPhotosComposable': {'baseUrl': 'https://photos.zillowstatic.com/fp/{photoKey}-p_e.jpg',
      'communityBaseUrl': None,
      'photoData': [{'photoKey': 'fee61d003178d968d58301b4a2249945'},
       {'photoKey': '746f37370be902f79e64dc4caf770704'},
       {'photoKey': '484591ba740df3d4d614d701d3318bc7'},
       {'photoKey': '83a334ae35010b4ab7ff491aa2b8856e'},
       {'photoKey': 'b977e8ca76ba8299b3819aa98afea262'},
       {'photoKey': 'fbbac5eae307060f6279a21a3e234be7'},
       {'photoKey': 'f3711a6450d11bc229993a9af1b9a589'},
       {'photoKey': '4bf45c39fe8ca44c8e4a70f5945f72e0'},
       {'photoKey': '1440bc462f6637086424fa261af0d923'},
       {'photoKey': '96f80b995d902227625c6e11aece067d'},
       {'photoKey': 'd305946d562e42348ab897603b918c61'},
       {'photoKey': 'd81410b36b0995810d2db57aa15ca7f9'},
       {'photoKey': '1c45caee5c254a7e7b52301a633ae048'},
       {'photoKey': 'e58d38a9b51deeecdb1efe959bcf8d2f'},
       {'photoKey': '7e43ade7e4e9109e3b480c8183a9bdad'},
       {'photoKey': '304766e3b4a32d6ec0507a451bfc23e2'},
       {'photoKey': '286cbd18d0f05847f951738cbc833838'},
       {'photoKey': '5dd9f322585f534113cca47ae13f1632'},
       {'photoKey': '55dffc94d8fc8190913743e6d04602d3'},
       {'photoKey': '63568d8deaacf77cea84bfbfb8f7434f'},
       {'photoKey': '31a58cfabc5192bca007d147093dd5aa'},
       {'photoKey': '67ce2fb0c3808140caaba9e51d3fda36'},
       {'photoKey': 'bc0f90ca478fd80afcd260432b916d8d'},
       {'photoKey': '6ec0ebdff0cbdd7edc5faa14505038da'},
       {'photoKey': '63a77838466e89ef5b02caf88d777c24'},
       {'photoKey': 'a057eaa1fb4e6ca3fbfbc9731fce09af'},
       {'photoKey': '18c95f788e95116e9e24fa4b5d8147e1'},
       {'photoKey': 'bfc8e8ce921d7f0aadf361b478645b03'},
       {'photoKey': 'f5705ab037bc4ec10802c78d23563675'},
       {'photoKey': '19ed022a2a02db68e12655ee6b25d57b'},
       {'photoKey': '26db078e096191d7ac17a50b42c1963e'}],
      'communityPhotoData': None,
      'isStaticUrls': False},
     'isPaidBuilderNewConstruction': False},
    {'zpid': '3577740',
     'palsId': '17001_12519153',
     'id': '3577740',
     'rawHomeStatusCd': 'ForSale',
     'marketingStatusSimplifiedCd': 'For Sale by Agent',
     'imgSrc': 'https://photos.zillowstatic.com/fp/97efafd9c5bd5fbe735cd2490dfacb07-p_e.jpg',
     'hasImage': True,
     'detailUrl': 'https://www.zillow.com/homedetails/7457-W-Ardmore-Ave-Chicago-IL-60631/3577740_zpid/',
     'statusType': 'FOR_SALE',
     'statusText': 'Active',
     'countryCurrency': '$',
     'price': '$500,000',
     'unformattedPrice': 500000,
     'address': '7457 W Ardmore Ave, Chicago, IL 60631',
     'addressStreet': '7457 W Ardmore Ave',
     'addressCity': 'Chicago',
     'addressState': 'IL',
     'addressZipcode': '60631',
     'isUndisclosedAddress': False,
     'shouldShowRequestOnPrice': False,
     'beds': 3,
     'baths': 2.0,
     'area': 0,
     'latLong': {'latitude': 41.984764, 'longitude': -87.81407},
     'isZillowOwned': False,
     'flexFieldText': 'Fully finished basement',
     'contentType': 'homeInsight',
     'hdpData': {'homeInfo': {'zpid': 3577740,
       'streetAddress': '7457 W Ardmore Ave',
       'zipcode': '60631',
       'city': 'Chicago',
       'state': 'IL',
       'latitude': 41.984764,
       'longitude': -87.81407,
       'price': 500000.0,
       'bathrooms': 2.0,
       'bedrooms': 3.0,
       'livingArea': 0.0,
       'homeType': 'SINGLE_FAMILY',
       'homeStatus': 'FOR_SALE',
       'daysOnZillow': 7,
       'isFeatured': False,
       'shouldHighlight': False,
       'listing_sub_type': {'is_FSBA': True},
       'isUnmappable': False,
       'isPreforeclosureAuction': False,
       'homeStatusForHDP': 'FOR_SALE',
       'priceForHDP': 500000.0,
       'timeOnZillow': 642958000,
       'isNonOwnerOccupied': True,
       'isPremierBuilder': False,
       'isZillowOwned': False,
       'currency': 'USD',
       'country': 'USA',
       'taxAssessedValue': 330000.0,
       'lotAreaValue': 4950.0,
       'lotAreaUnit': 'sqft',
       'isShowcaseListing': False}},
     'isSaved': False,
     'isUserClaimingOwner': False,
     'isUserConfirmedClaim': False,
     'pgapt': 'ForSale',
     'sgapt': 'For Sale (Broker)',
     'shouldShowZestimateAsPrice': False,
     'has3DModel': False,
     'hasVideo': False,
     'isHomeRec': False,
     'hasAdditionalAttributions': True,
     'isFeaturedListing': False,
     'isShowcaseListing': False,
     'list': True,
     'relaxed': False,
     'brokerName': "@properties Christie's International Real Estate",
     'carouselPhotosComposable': {'baseUrl': 'https://photos.zillowstatic.com/fp/{photoKey}-p_e.jpg',
      'communityBaseUrl': None,
      'photoData': [{'photoKey': '97efafd9c5bd5fbe735cd2490dfacb07'},
       {'photoKey': '6b3f08a3488ff4d1d6d0f896677e3a87'},
       {'photoKey': 'b8a51cbc628948547fb411bbc7185958'},
       {'photoKey': 'bd0f75a8dbc3f4d6a3b097f5c52305df'},
       {'photoKey': '0aaa67071aa98defd4957e0b5bab480e'},
       {'photoKey': '640774127887fa5e7186579106ace01f'},
       {'photoKey': '43055f79fbf3b823946d7145bfc60541'},
       {'photoKey': 'bb20a7cdf2d223a5a7b281fc8d3d40fe'},
       {'photoKey': '7eb287eec3a20555a2430059ac570f34'},
       {'photoKey': '61957b8c20fb22a9f55116ff864f9656'},
       {'photoKey': 'f8405536aac0c72b3c8407d8203fe278'},
       {'photoKey': '4a05f4a7d99dd0564d21e105c1722ebe'},
       {'photoKey': '8659b8573dccf5809a20ad38c8ce3917'},
       {'photoKey': 'e440910a15326b2d9ac7b0cb16327efe'},
       {'photoKey': 'b8f21d1d59194baea79533b269347d7d'},
       {'photoKey': 'f00073439fc4399e94327227b6b6734f'},
       {'photoKey': '6aca79c1043dd844f8ddaaffd229d6cd'},
       {'photoKey': '08914edb396d35d66c1efaced270d7ba'},
       {'photoKey': 'd72182a0198218b7d6614cc6b8a30048'},
       {'photoKey': 'bf35fed7a3cfb1d83ff7bbcafbed4319'},
       {'photoKey': '0e27801dbb906bf6993e9f7eb6609556'},
       {'photoKey': '5f058c601528e156189abe7c500f962a'},
       {'photoKey': '9158ff0b2a320cbc8fd662d855131a9f'},
       {'photoKey': 'a0561340ba7d95d3cfb8588276fc4b62'},
       {'photoKey': '48eaa9d57c39d02c2e3cd5f1fd610c33'},
       {'photoKey': '2627a684d14a95f56f7715af192e9c9f'},
       {'photoKey': 'b00a01bdd8774d93e8a6b89885bfbd0d'},
       {'photoKey': '6397ccdbd06cf1ef9b6aba518fe07f11'},
       {'photoKey': '7d1908644a16bfec97301cfe580ec0a5'},
       {'photoKey': '1b753337fc10b894d6765562e859b14f'},
       {'photoKey': 'c154026a00eaa2e86fcb265259e85f3b'},
       {'photoKey': '57851d01a3c5308e8d352014cb5d66e8'}],
      'communityPhotoData': None,
      'isStaticUrls': False},
     'isPaidBuilderNewConstruction': False},
    {'zpid': '441034809',
     'palsId': '17001_12507397',
     'id': '441034809',
     'rawHomeStatusCd': 'ForSale',
     'marketingStatusSimplifiedCd': 'For Sale by Agent',
     'imgSrc': 'https://photos.zillowstatic.com/fp/1c9248bfd70c8736716e0356e60af141-p_e.jpg',
     'hasImage': True,
     'detailUrl': 'https://www.zillow.com/homedetails/548-W-Oakdale-Ave-Chicago-IL-60657/441034809_zpid/',
     'statusType': 'FOR_SALE',
     'statusText': 'New',
     'countryCurrency': '$',
     'price': '$950,000',
     'unformattedPrice': 950000,
     'address': '548 W Oakdale Ave, Chicago, IL 60657',
     'addressStreet': '548 W Oakdale Ave',
     'addressCity': 'Chicago',
     'addressState': 'IL',
     'addressZipcode': '60657',
     'isUndisclosedAddress': False,
     'shouldShowRequestOnPrice': False,
     'beds': 4,
     'baths': 4.0,
     'area': 0,
     'latLong': {'latitude': 41.93581, 'longitude': -87.64374},
     'isZillowOwned': False,
     'flexFieldText': 'High ceilings',
     'contentType': 'homeInsight',
     'hdpData': {'homeInfo': {'zpid': 441034809,
       'streetAddress': '548 W Oakdale Ave',
       'zipcode': '60657',
       'city': 'Chicago',
       'state': 'IL',
       'latitude': 41.93581,
       'longitude': -87.64374,
       'price': 950000.0,
       'bathrooms': 4.0,
       'bedrooms': 4.0,
       'livingArea': 0.0,
       'homeType': 'SINGLE_FAMILY',
       'homeStatus': 'FOR_SALE',
       'daysOnZillow': 4,
       'isFeatured': False,
       'shouldHighlight': False,
       'listing_sub_type': {'is_FSBA': True},
       'isUnmappable': False,
       'isPreforeclosureAuction': False,
       'homeStatusForHDP': 'FOR_SALE',
       'priceForHDP': 950000.0,
       'timeOnZillow': 368452000,
       'isNonOwnerOccupied': True,
       'isPremierBuilder': False,
       'isZillowOwned': False,
       'currency': 'USD',
       'country': 'USA',
       'taxAssessedValue': 1120000.0,
       'lotAreaValue': 3500.0,
       'lotAreaUnit': 'sqft',
       'isShowcaseListing': False}},
     'isSaved': False,
     'isUserClaimingOwner': False,
     'isUserConfirmedClaim': False,
     'pgapt': 'ForSale',
     'sgapt': 'For Sale (Broker)',
     'shouldShowZestimateAsPrice': False,
     'has3DModel': False,
     'hasVideo': False,
     'isHomeRec': False,
     'hasAdditionalAttributions': True,
     'isFeaturedListing': False,
     'isShowcaseListing': False,
     'list': True,
     'relaxed': False,
     'brokerName': "Jameson Sotheby's Intl Realty",
     'carouselPhotosComposable': {'baseUrl': 'https://photos.zillowstatic.com/fp/{photoKey}-p_e.jpg',
      'communityBaseUrl': None,
      'photoData': [{'photoKey': '1c9248bfd70c8736716e0356e60af141'},
       {'photoKey': '9dbf9015497cbd5c5ad27b9711a1b8e7'},
       {'photoKey': '5f2bc23c40f5d08215b248e6c57744fe'},
       {'photoKey': '3f7231b8e67fb3145cccaa068b8e4c9a'},
       {'photoKey': '41d2490796d4b73140ee5c0f950e979e'},
       {'photoKey': '6de5ab1e428be5cf696b7c5d139301b1'},
       {'photoKey': '2c1f01ae295ee1f97dd3355e266db107'},
       {'photoKey': 'c3d76ff7853a7da42f2f2cc16bce2086'},
       {'photoKey': 'e7021ad1c2ff44ed4b9a766909740351'},
       {'photoKey': 'f281a63d435311f73fd3909e7715dd38'},
       {'photoKey': 'c3c5a3ab84b334c11a126cf1fc8a1491'},
       {'photoKey': '1ee18b720174ab38f64df28ff9433044'},
       {'photoKey': '31244046bbdd71c4f9615b730f0720e8'},
       {'photoKey': 'e51b616d74ab14453e0fc0853e22eb55'},
       {'photoKey': '7388eb13fc81b1d8fc7882016fc5b80e'},
       {'photoKey': '1d383cafc539578931e33deb11568a3e'},
       {'photoKey': 'a97c40242c994bbf5438182f9ff2ffdb'},
       {'photoKey': 'd7bbc00ba93303d41bcb346b4430368a'},
       {'photoKey': '4723f2cc0c73c5079e4c789d48e86b98'},
       {'photoKey': 'fe8f486262508c2a2f494bd4cd071f1a'},
       {'photoKey': '181f68f230ec58246a78c701c831428d'},
       {'photoKey': 'd6c1e464575d9a87c14d62e026db406f'},
       {'photoKey': 'f92ded812fd799177a5cdd54421cffa5'}],
      'communityPhotoData': None,
      'isStaticUrls': False},
     'isPaidBuilderNewConstruction': False},
    {'zpid': '2078946235',
     'palsId': '17001_12525317',
     'id': '2078946235',
     'rawHomeStatusCd': 'ForSale',
     'marketingStatusSimplifiedCd': 'For Sale by Agent',
     'imgSrc': 'https://photos.zillowstatic.com/fp/b8a8ff77de8c6892f4757d016bf25d58-p_e.jpg',
     'hasImage': True,
     'detailUrl': 'https://www.zillow.com/homedetails/948-W-Sheridan-Rd-2D-Chicago-IL-60613/2078946235_zpid/',
     'statusType': 'FOR_SALE',
     'statusText': 'New',
     'countryCurrency': '$',
     'price': '$429,900',
     'unformattedPrice': 429900,
     'address': '948 W Sheridan Rd #2D, Chicago, IL 60613',
     'addressStreet': '948 W Sheridan Rd #2D',
     'addressCity': 'Chicago',
     'addressState': 'IL',
     'addressZipcode': '60613',
     'isUndisclosedAddress': False,
     'shouldShowRequestOnPrice': False,
     'beds': 2,
     'baths': 2.0,
     'area': 1300,
     'latLong': {'latitude': 41.95294, 'longitude': -87.65408},
     'isZillowOwned': False,
     'flexFieldText': 'Cozy gas fireplace',
     'contentType': 'homeInsight',
     'hdpData': {'homeInfo': {'zpid': 2078946235,
       'streetAddress': '948 W Sheridan Rd #2D',
       'zipcode': '60613',
       'city': 'Chicago',
       'state': 'IL',
       'latitude': 41.95294,
       'longitude': -87.65408,
       'price': 429900.0,
       'bathrooms': 2.0,
       'bedrooms': 2.0,
       'livingArea': 1300.0,
       'homeType': 'CONDO',
       'homeStatus': 'FOR_SALE',
       'daysOnZillow': 4,
       'isFeatured': False,
       'shouldHighlight': False,
       'listing_sub_type': {'is_FSBA': True},
       'isUnmappable': False,
       'isPreforeclosureAuction': False,
       'homeStatusForHDP': 'FOR_SALE',
       'priceForHDP': 429900.0,
       'timeOnZillow': 381063000,
       'isNonOwnerOccupied': True,

In [ ]:
# view count of properies returned in request
num_of_properties = listing_response.json()["data"]["categoryTotals"]["cat1"]["totalResultCount"]
print("Count of properties:", num_of_properties)

Count of properties: 5365

In [ ]:
listing_response.json()["data"]["cat1"]["searchResults"]['mapResults'][76]

IndexError: list index out of range

In [ ]:
# view all listings
df_listings = pd.json_normalize(listing_response.json()["data"]["cat1"]["searchResults"]["mapResults"])
print("Number of rows:", len(df_listings))
print("Number of columns:", len(df_listings.columns))
df_listings.columns

Number of rows: 75
Number of columns: 95

Index(['zpid', 'palsId', 'rawHomeStatusCd', 'marketingStatusSimplifiedCd',
       'imgSrc', 'hasImage', 'detailUrl', 'statusType', 'statusText', 'price',
       'priceLabel', 'address', 'addressState', 'shouldShowRequestOnPrice',
       'beds', 'baths', 'area', 'flexFieldText', 'contentType',
       'isUserClaimingOwner', 'isUserConfirmedClaim', 'pgapt', 'sgapt',
       'shouldShowZestimateAsPrice', 'has3DModel', 'hasVideo', 'isHomeRec',
       'hasAdditionalAttributions', 'isFeaturedListing', 'isShowcaseListing',
       'listingType', 'isFavorite', 'visited', 'brokerName', 'timeOnZillow',
       'isPaidBuilderNewConstruction', 'latLong.latitude', 'latLong.longitude',
       'hdpData.homeInfo.zpid', 'hdpData.homeInfo.streetAddress',
       'hdpData.homeInfo.zipcode', 'hdpData.homeInfo.city',
       'hdpData.homeInfo.state', 'hdpData.homeInfo.latitude',
       'hdpData.homeInfo.longitude', 'hdpData.homeInfo.price',
       'hdpData.homeInfo.bathrooms', 'hdpData.homeInfo.bedrooms',
       'hdpData.homeInfo.livingArea', 'hdpData.homeInfo.homeType',
       'hdpData.homeInfo.homeStatus', 'hdpData.homeInfo.daysOnZillow',
       'hdpData.homeInfo.isFeatured', 'hdpData.homeInfo.shouldHighlight',
       'hdpData.homeInfo.listing_sub_type.is_FSBA',
       'hdpData.homeInfo.isUnmappable',
       'hdpData.homeInfo.isPreforeclosureAuction',
       'hdpData.homeInfo.homeStatusForHDP', 'hdpData.homeInfo.priceForHDP',
       'hdpData.homeInfo.timeOnZillow', 'hdpData.homeInfo.isNonOwnerOccupied',
       'hdpData.homeInfo.isPremierBuilder', 'hdpData.homeInfo.isZillowOwned',
       'hdpData.homeInfo.currency', 'hdpData.homeInfo.country',
       'hdpData.homeInfo.taxAssessedValue', 'hdpData.homeInfo.unit',
       'hdpData.homeInfo.isShowcaseListing', 'hdpData.homeInfo.lotAreaValue',
       'hdpData.homeInfo.lotAreaUnit', 'hdpData.homeInfo.datePriceChanged',
       'hdpData.homeInfo.priceReduction', 'hdpData.homeInfo.priceChange',
       'hdpData.homeInfo.listing_sub_type.is_openHouse',
       'hdpData.homeInfo.openHouse',
       'hdpData.homeInfo.open_house_info.open_house_showing',
       'hdpData.homeInfo.zestimate', 'hdpData.homeInfo.rentZestimate',
       'minBeds', 'minBaths', 'minArea', 'lotId', 'buildingId', 'isBuilding',
       'canSaveBuilding', 'unitCount', 'listPriceIncludesRequiredMonthlyFees',
       'lotAreaString', 'hdpData.homeInfo.isRentalWithBasePrice',
       'hdpData.homeInfo.listing_sub_type.is_forAuction', 'streetViewURL',
       'streetViewMetadataURL', 'hdpData.homeInfo.listing_sub_type.is_newHome',
       'hdpData.homeInfo.newConstructionType',
       'hdpData.homeInfo.listing_sub_type.is_bankOwned'],
      dtype='object')

In [ ]:
# view price
px.histogram(df_listings, x="hdpData.homeInfo.price", title="Sales Price Histogram")

In [ ]:
# view zestimate
px.histogram(df_listings, x="hdpData.homeInfo.zestimate", title="Zestimate Histogram")

In [ ]:
# view rent zestimate
px.box(df_listings, x="hdpData.homeInfo.rentZestimate", title="Rent Zestimate Box Plot")

### <font color="green">2. Rental Property Listings For Rent</font>

In [ ]:
# zillow search url
rent_listing_url = "https://www.zillow.com/tampa-fl/rentals/?searchQueryState=%7B%22pagination%22%3A%7B%7D%2C%22usersSearchTerm%22%3A%22Tampa%2C%20FL%22%2C%22mapBounds%22%3A%7B%22west%22%3A-82.69632304150392%2C%22east%22%3A-82.2122379584961%2C%22south%22%3A27.743327003864252%2C%22north%22%3A28.2453440906427%7D%2C%22regionSelection%22%3A%5B%7B%22regionId%22%3A41176%2C%22regionType%22%3A6%7D%5D%2C%22isMapVisible%22%3Atrue%2C%22filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22priorityscore%22%7D%2C%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22fsbo%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22pmf%22%3A%7B%22value%22%3Afalse%7D%2C%22pf%22%3A%7B%22value%22%3Afalse%7D%2C%22fr%22%3A%7B%22value%22%3Atrue%7D%2C%22beds%22%3A%7B%22min%22%3A3%2C%22max%22%3A3%7D%2C%22baths%22%3A%7B%22min%22%3A2%7D%2C%22apco%22%3A%7B%22value%22%3Afalse%7D%2C%22apa%22%3A%7B%22value%22%3Afalse%7D%2C%22con%22%3A%7B%22value%22%3Afalse%7D%2C%22tow%22%3A%7B%22value%22%3Afalse%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A11%7D"

# get listings
rent_listing_response = get_listings(api_key, rent_listing_url)

In [ ]:
# view all keys
print(rent_listing_response.json().keys())

# check if request is successful
print("Request success:", rent_listing_response.json()["is_success"])

# view count of properies returned in request
num_of_properties = rent_listing_response.json()["data"]["categoryTotals"]["cat1"]["totalResultCount"]
print("Count of properties:", num_of_properties)

dict_keys(['is_success', 'data', 'message', 'info'])
Request success: True
Count of properties: 399

In [ ]:
# view all listings
df_rent_listings = pd.json_normalize(rent_listing_response.json()["data"]["cat1"]["searchResults"]["mapResults"])
print("Number of rows:", len(df_rent_listings))
print("Number of columns:", len(df_rent_listings.columns))
df_rent_listings

Number of rows: 75
Number of columns: 81

,zpid,palsId,rawHomeStatusCd,marketingStatusSimplifiedCd,imgSrc,hasImage,detailUrl,statusType,statusText,price,priceLabel,address,addressState,shouldShowRequestOnPrice,beds,baths,area,isUserClaimingOwner,isUserConfirmedClaim,pgapt,sgapt,shouldShowZestimateAsPrice,has3DModel,hasVideo,isHomeRec,hasAdditionalAttributions,isFeaturedListing,isShowcaseListing,listingType,isFavorite,availabilityDate,visited,timeOnZillow,rentalMarketingSubType,marketingTreatments,isPaidBuilderNewConstruction,latLong.latitude,latLong.longitude,listCardRecommendation.flexFieldRecommendations,hdpData.homeInfo.zpid,hdpData.homeInfo.streetAddress,hdpData.homeInfo.zipcode,hdpData.homeInfo.city,hdpData.homeInfo.state,hdpData.homeInfo.latitude,hdpData.homeInfo.longitude,hdpData.homeInfo.price,hdpData.homeInfo.bathrooms,hdpData.homeInfo.bedrooms,hdpData.homeInfo.livingArea,hdpData.homeInfo.homeType,hdpData.homeInfo.homeStatus,hdpData.homeInfo.daysOnZillow,hdpData.homeInfo.isFeatured,hdpData.homeInfo.shouldHighlight,hdpData.homeInfo.isRentalWithBasePrice,hdpData.homeInfo.zestimate,hdpData.homeInfo.rentZestimate,hdpData.homeInfo.isUnmappable,hdpData.homeInfo.isPreforeclosureAuction,hdpData.homeInfo.homeStatusForHDP,hdpData.homeInfo.priceForHDP,hdpData.homeInfo.timeOnZillow,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.country,hdpData.homeInfo.taxAssessedValue,hdpData.homeInfo.isShowcaseListing,factsAndFeatures.fullBathroomCount,factsAndFeatures.hasFireplace,factsAndFeatures.hasAirConditioning,factsAndFeatures.hasSpa,factsAndFeatures.hasPool,factsAndFeatures.halfBathroomCount,hdpData.homeInfo.datePriceChanged,hdpData.homeInfo.priceReduction,hdpData.homeInfo.priceChange,hdpData.homeInfo.lotAreaValue,hdpData.homeInfo.lotAreaUnit
0,45100344,100066001_9557829aeb2ea8c7c2a66616113f287d3eb3...,ForRent,For Rent,https://photos.zillowstatic.com/fp/75036ef4123...,True,/homedetails/2510-E-28th-Ave-Tampa-FL-33605/45...,FOR_RENT,House for rent,"$1,950/mo",$2.0K,"2510 E 28th Ave, Tampa, FL 33605",FL,False,3,2.0,1250,False,False,ForRent,For Rent,False,False,False,False,False,True,False,,False,2025-12-04 00:00:00,False,367504000,unknown,"[paid, zillowRentalManager]",False,27.976164,-82.430916,"[{'displayString': '4 days ago', 'contentType'...",45100344,2510 E 28th Ave,33605,Tampa,FL,27.976164,-82.430916,1950.0,2.0,3.0,1250.0,SINGLE_FAMILY,FOR_RENT,4,True,False,False,270500.0,2044,False,False,FOR_RENT,1950.0,367504000,True,False,False,USD,USA,210810.0,False,2,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
1,45102953,100066001_ad40befc54e4a8f1b81b4122cef96420847b...,ForRent,For Rent,https://photos.zillowstatic.com/fp/632a6fce324...,True,/homedetails/1321-W-Nassau-St-Tampa-FL-33607/4...,FOR_RENT,House for rent,"$3,000/mo",$3.0K,"1321 W Nassau St, Tampa, FL 33607",FL,False,3,2.0,1276,False,False,ForRent,For Rent,False,False,False,False,False,True,False,,False,2025-12-05 00:00:00,False,266324000,unknown,"[paid, zillowRentalManager]",False,27.953663,-82.474236,"[{'displayString': '3 days ago', 'contentType'...",45102953,1321 W Nassau St,33607,Tampa,FL,27.953663,-82.474236,3000.0,2.0,3.0,1276.0,SINGLE_FAMILY,FOR_RENT,3,True,False,False,495800.0,2489,False,False,FOR_RENT,3000.0,266324000,True,False,False,USD,USA,372569.0,False,2,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
2,45056651,100066001_b655c53aef5f614f2b2d7fd2401bcbf6bd77...,ForRent,For Rent,https://photos.zillowstatic.com/fp/c0d4be21d75...,True,/homedetails/4012-W-San-Juan-St-Tampa-FL-33629...,FOR_RENT,House for rent,"$3,900/mo",$3.9K,"4012 W San Juan St, Tampa, FL 33629",FL,False,3,2.0,1200,False,False,ForRent,For Rent,False,False,False,False,False,True,False,,False,2026-02-01 00:00:00,False,298928000,unknown,"[paid, zillowRentalManager]",False,27.918220,-82.511180,"[{'displayString': '3 days ago', 'contentType'...",45056651,4012 W San Juan St,33629,Tampa,FL,27.918220,-82.511180,3900.0,2.0,3.0,1200.0,SINGLE_FAMILY,FOR_RENT,3,True,False,False,570600.0,2509,False,False,FOR_RENT,3900.0,298928000,True,False,False,USD,USA,379041.0,False,2,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
3,44860141,100066001_36e58e804d5dce638daee02027d09cd91b7b...,ForRent,For Rent,https://photos.zillowstatic.com/fp/d3cd951afa1...,True,/homedetails/8709-Huntfield-St-Tampa-FL-33635/...,FOR_RENT,House for rent,"$3,025/mo",$3.0K,"8709 Huntfield St, Tampa, FL 33635",FL,False,3,2.0,1588,False,False,ForRent,For Rent,False,False,False,False,False,True,False,,False,2025-12-01 00:00:00,False,2717757000,unknown,"[paid, zillowRentalManager]",False,28.035177,-82.599470,"[{'displayString': 'Apply instantly', 'content...",44860141,8709 Huntfield St,33635,Tampa,FL,28.035177,-82.599470,3025.0,2.0,3.0,1588.0,SINGLE_FAMILY,FOR_RENT,31,True,False,False,345400.0,2641,False,False,FOR_RENT,3025.0,2717757000,True,False,False,USD,USA,347679.0,False,2,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
4,45111954,100066001_afc4b264f7579a2dcdc323f3c9e2f2a0c662...,ForRent,For Rent,https://photos.zillowstatic.com/fp/43500018024...,True,/homedetails/501-Columbia-Dr-Tampa-FL-33606/45...,FOR_RENT,House for rent,"$7,000/mo",$7.0K,"501 Columbia Dr, Tampa, FL 33606",FL,False,3,3.0,1890,False,False,ForRent,For Rent,False,False,False,False,False,True,False,,False,2025-12-15 00:00:00,False,619179000,unknown,"[paid, zillowRentalManager]",False,27.923702,-82.450460,"[{'displayString': '7 days ago', 'contentType'...",45111954,501 Columbia Dr,33606,Tampa,FL,27.923702,-82.450460,7000.0,3.0,3.0,1890.0,SINGLE_FAMILY,FOR_RENT,7,True,False,False,1193300.0,6699,False,False,FOR_RENT,7000.0,619179000,True,False,False,USD,USA,740281.0,False,2,False,False,False,False,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,44933684,100066001_ba40ca3239c5199b3b79a4d8b7bb497b993f...,ForRent,For Rent,https://photos.zillowstatic.com/fp/f7ed579cf0c...,True,/homedetails/5614-Kenny-Dr-Tampa-FL-33617/4493...,FOR_RENT,House for rent,"$2,700/mo",$2.7K,"5614 Kenny Dr, Tampa, FL 33617",FL,False,3,2.0,2101,False,False,ForRent,For Rent,False,False,False,False,False,True,False,,False,NaN,False,2981645000,unknown,"[paid, zillowRentalManager]",False,28.016527,-82.391190,NaN,44933684,5614 Kenny Dr,33617,Tampa,FL,28.016527,-82.391190,2700.0,2.0,3.0,2101.0,SINGLE_FAMILY,FOR_RENT,34,True,False,False,509700.0,2948,False,False,FOR_RENT,2700.0,2981645000,True,False,False,USD,USA,288845.0,False,2,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN
71,45104650,100066001_da740ea16539585233c8ff5c25148db6c2c0...,ForRent,For Rent,https://photos.zillowstatic.com/fp/a4af4f30a9a...,True,/homedetails/2509-W-Grace-St-Tampa-FL-33607/45...,FOR_RENT,House for rent,"$2,750/mo",$2.8K,"2509 W Grace St, Tampa, FL 33607",FL,False,3,2.0,1444,False,False,ForRent,For Rent,False,False,False,False,False,True,False,,False,2025-11-20 00:00:00,False,2996176000,unknown,"[trustedListing, paid, singleFamilyPaid, feedC...",False,27.953047,-82.485954,NaN,45104650,2509 W Grace St,33607,Tampa,FL,27.953047,-82.485954,2750.0,2.0,3.0,1444.0,SINGLE_FAMILY,FOR_RENT,34,True,False,False,453900.0,2984,False,False,FOR_RENT,2750.0,2996176000,True,False,False,USD,USA,393594.0,False,2,False,False,False,False,0.0,1.763194e+12,$15 (Nov 15),-15.0,4748.04,sqft
72,44869515,100066001_d066e5410b623788eb90139b0b6c652ea51c...,ForRent,For Rent,https://photos.zillowstatic.com/fp/ae4e8a6b7ff...,True,/homedetails/6529-Seafairer-Dr-Tampa-FL-33615/...,FOR_RENT,House for rent,"$2,649/mo",$2.6K,"6529 Seafairer Dr, Tampa, FL 33615",FL,False,3,2.0,1718,False,False,ForRent,For Rent,False,False,False,False,False,True,False,,False,NaN,False,410430000,unknown,"[trustedListing, paid, singleFamilyPaid, feedC...",False,28.010508,-82.605880,"[{'displayString': '4 days ago', 'contentType'...",44869515,6529 Seafairer Dr,33615,Tampa,FL,28.010508,-82.605880,2649.0,2.0,3.0,1718.0,SINGLE_FAMILY,FOR_RENT,4,True,False,False,405300.0,2110,False,False,FOR_RENT,2649.0,410430000,True,False,False,USD,USA,326551.0,False,2,False,False,False,False,0.0,1.764922e+12,$46 (Dec 5),-46.0,NaN,NaN
73,2060822423,100066001_729dc2da8b6b58ddb75976a877f537572e7c...,ForRent,For Rent,https://photos.zillowstatic.com/fp/678225e7984...,True,/homedetails/10214-N-Blvd-Tampa-FL-33612/20608...,FOR_RENT,House for rent,"$2,010/mo",$2.0K,"10214 N Blvd, Tampa, FL 33612",FL,False,3,2.0,1132,False,False,ForRent,For Rent,False,True,False,False,False,True,False,,False,2025-12-16 00:00:00,False,2506966000,unknown,"[trustedListing, paid, singleFamilyPaid, feedC...",False,28.042260,-82.467810,"[{'displayString': '3D Tour', 'contentType': '...",2060822423,10214 N Blvd,33612,Tampa,FL,28.042260,-82.467810,2010.0,2.0,3.0,1132.0,SINGLE_FAMILY,FOR_RENT,29,True,False,False,313600.0,2304,False,False,FOR_RENT,2010.0,2506966000,True,False,False,USD,USA,NaN,False,2,False,False,False,False,0.0,1.764576e+12,$50 (Dec 1),-50.0,NaN,NaN
74,58433223,100066001_56c70f25c081e0af8388783868b683cda1eb...,ForRent,For Rent,https://photos.zillowstatic.com/fp/6b61b94d886...,True,/homedetails/5817-Mohr-Loop-Tampa-FL-33615/584...,FOR_RENT,House for rent,"$2,490/mo",$2.5K,"5817 Mohr Loop, Tampa, FL 33615",FL,False,3,2.0,1530,False,False,ForRent,For Rent,False,True,False,False,False,True,False,,False,2025-11-13 00:00:00,False,2447674000,unknown,"[trustedListing, paid, singleFamilyPaid, feedC...",False,28.003020,-82.586380,"[{'displayString': '3D Tour', 'contentType': '...",58433223,5817 Mohr Loop,33615,Tampa,FL,28.003020,-82.586380,2490.0,2.0,3.0,1530.0,SINGLE_FAMILY,FOR_RENT,28,True,False,False,354400.0,2481,False,False,FOR_RENT,2490.0,2447674000,True,False,False,USD,USA,293142.0,False,2,False,False,False,False,0.0,1.764058e+12,$40 (Nov 25),-40.0,NaN,NaN

In [ ]:
# view price
px.box(df_rent_listings, x="hdpData.homeInfo.price", title="Rental Price Box Plot")

In [ ]:
# view rent zestimate
px.box(df_rent_listings, x="hdpData.homeInfo.rentZestimate", title="Rent Zestimate Box Plot")

### <font color="green">3. Property Details</font>

In [ ]:
# property unique id
zpid = "99616959"

# get property detail
prop_detail_response = get_property_detail(api_key, zpid)

In [ ]:
# view all keys
print(prop_detail_response.json().keys())

# check if request is successful
print("Request success:", prop_detail_response.json()["is_success"])

dict_keys(['is_success', 'data', 'message'])
Request success: True

In [ ]:
# view property details
df_prop = pd.json_normalize(prop_detail_response.json()['data'])
print("Number of rows:", len(df_prop))
print("Number of columns:", len(df_prop.columns))
df_prop

Number of rows: 1
Number of columns: 602

,listingDataSource,zpid,city,state,homeStatus,isListingClaimedByCurrentSignedInUser,isCurrentSignedInAgentResponsible,bedrooms,bathrooms,price,yearBuilt,streetAddress,zipcode,isCurrentSignedInUserVerifiedOwner,regionString,propertyUpdatePageLink,moveHomeMapLocationLink,propertyEventLogLink,editPropertyHistorylink,isRentalListingOffMarket,hdpUrl,nearbyCities,nearbyNeighborhoods,country,nearbyZipcodes,abbreviatedAddress,building,isUndisclosedAddress,boroughId,providerListingID,boroughSearchUrl,communityUrl,isPremierBuilder,isZillowOwned,homeType,currency,listPriceLow,livingArea,livingAreaValue,zestimate,newConstructionType,zestimateLowPercent,zestimateHighPercent,rentZestimate,restimateLowPercent,restimateHighPercent,schools,homeValues,nearbyHomes,countyFIPS,parcelId,taxHistory,priceHistory,comps,description,whatILove,contingentListingType,timeOnZillow,pageViewCount,favoriteCount,daysOnZillow,latitude,longitude,openHouseSchedule,desktopWebHdpImageLink,brokerageName,timeZone,pals,listingAccountUserId,homeInsights,sellingSoon,listingProvider,isIncomeRestricted,brokerId,ssid,monthlyHoaFee,propertyTaxRate,hiResImageLink,hdpTypeDimension,mlsid,propertyTypeDimension,mediumImageLink,enhancedBrokerImageUrl,responsivePhotos,buildingId,virtualTourUrl,hasApprovedThirdPartyVirtualTourUrl,photoCount,livingAreaUnits,lotSize,lotAreaValue,lotAreaUnits,postingProductType,marketingName,richMedia,cityId,stateId,zipPlusFour,numberOfUnitsTotal,foreclosureDefaultFilingDate,foreclosureAuctionFilingDate,foreclosureLoanDate,foreclosureLoanOriginator,foreclosureLoanAmount,foreclosurePriorSaleDate,foreclosurePriorSaleAmount,foreclosureBalanceReportingDate,foreclosurePastDueBalance,foreclosureUnpaidBalance,foreclosureAuctionTime,foreclosureAuctionDescription,foreclosureAuctionCity,foreclosureAuctionLocation,foreclosureDate,foreclosureAmount,foreclosingBank,foreclosureJudicialType,datePostedString,foreclosureMoreInfo,hasBadGeocode,streetViewMetadataUrlMediaWallLatLong,streetViewMetadataUrlMediaWallAddress,streetViewTileImageUrlMediumLatLong,streetViewTileImageUrlMediumAddress,streetViewServiceUrl,postingUrl,hasPublicVideo,primaryPublicVideo,richMediaVideos,photos,tourViewCount,listingAccount,listingFeedID,livingAreaUnitsShort,priceChange,priceChangeDate,priceChangeDateString,hideZestimate,comingSoonOnMarketDate,isPreforeclosureAuction,lastSoldPrice,isHousingConnector,responsivePhotosOriginalRatio,streetViewMetadataUrlMapLightboxAddress,thumb,isRecentStatusChange,isNonOwnerOccupied,county,isFeatured,rentalApplicationsAcceptedType,listingTypeDimension,featuredListingTypeDimension,brokerIdDimension,keystoneHomeStatus,pageUrlFragment,isRentalsLeadCapMet,isPaidMultiFamilyBrokerId,address.streetAddress,address.city,address.state,address.zipcode,address.neighborhood,address.community,address.subdivision,listing_sub_type.is_newHome,listing_sub_type.is_FSBO,listing_sub_type.is_FSBA,listing_sub_type.is_foreclosure,listing_sub_type.is_bankOwned,listing_sub_type.is_forAuction,listing_sub_type.is_comingSoon,listing_sub_type.is_pending,listing_sub_type.is_openHouse,citySearchUrl.text,citySearchUrl.path,zipcodeSearchUrl.path,apartmentsForRentInZipcodeSearchUrl.path,housesForRentInZipcodeSearchUrl.path,neighborhoodRegion.name,neighborhoodSearchUrl.path,stateSearchUrl.path,countySearchUrl.text,countySearchUrl.path,adTargets.aamgnrc1,adTargets.bd,adTargets.fsbid,adTargets.city,adTargets.proptp,adTargets.pid,adTargets.lot,adTargets.zestibuck,adTargets.listtp,adTargets.sqftrange,adTargets.price,adTargets.sqft,adTargets.state,adTargets.mlong,adTargets.cnty,adTargets.prange,adTargets.zip,adTargets.mlat,adTargets.zusr,adTargets.price_band,adTargets.yrblt,adTargets.zestimate,adTargets.premieragent,adTargets.dma,adTargets.guid,adTargets.ssid,resoFacts.accessibilityFeatures,resoFacts.additionalFeeInfo,resoFacts.associationFee,resoFacts.associationAmenities,resoFacts.associationFee2,resoFacts.associationFeeIncludes,resoFacts.associationName,resoFacts.associationName2,resoFacts.associationPhone,resoFacts.associationPhone2,resoFacts.basementYN,resoFacts.buildingName,resoFacts.buyerAgencyCompensation,resoFacts.buyerAgencyCompensationType,resoFacts.appliances,resoFacts.atAGlanceFacts,resoFacts.attic,resoFacts.availabilityDate,resoFacts.basement,resoFacts.bathrooms,resoFacts.bathroomsFull,resoFacts.bathroomsHalf,resoFacts.bathroomsOneQuarter,resoFacts.bathroomsPartial,resoFacts.bathroomsThreeQuarter,resoFacts.bedrooms,resoFacts.bodyType,resoFacts.canRaiseHorses,resoFacts.carportParkingCapacity,resoFacts.cityRegion,resoFacts.commonWalls,resoFacts.communityFeatures,resoFacts.cooling,resoFacts.coveredParkingCapacity,resoFacts.cropsIncludedYN,resoFacts.developmentStatus,resoFacts.doorFeatures,resoFacts.electric,resoFacts.elevation,resoFacts.elevationUnits,resoFacts.entryLevel,resoFacts.entryLocation,resoFacts.exclusions,resoFacts.fencing,resoFacts.fireplaceFeatures,resoFacts.fireplaces,resoFacts.flooring,resoFacts.foundationArea,resoFacts.furnished,resoFacts.garageParkingCapacity,resoFacts.gas,resoFacts.greenBuildingVerificationType,resoFacts.greenEnergyEfficient,resoFacts.greenIndoorAirQuality,resoFacts.greenSustainability,resoFacts.greenWaterConservation,resoFacts.hasAssociation,resoFacts.hasAttachedGarage,resoFacts.hasAttachedProperty,resoFacts.hasCooling,resoFacts.hasCarport,resoFacts.hasElectricOnProperty,resoFacts.hasFireplace,resoFacts.hasGarage,resoFacts.hasHeating,resoFacts.hasLandLease,resoFacts.hasOpenParking,resoFacts.hasSpa,resoFacts.hasPrivatePool,resoFacts.hasView,resoFacts.hasWaterfrontView,resoFacts.heating,resoFacts.highSchool,resoFacts.highSchoolDistrict,resoFacts.hoaFee,resoFacts.homeType,resoFacts.horseAmenities,resoFacts.horseYN,resoFacts.interiorFeatures,resoFacts.irrigationWaterRightsAcres,resoFacts.irrigationWaterRightsYN,resoFacts.isSeniorCommunity,resoFacts.landLeaseAmount,resoFacts.landLeaseExpirationDate,resoFacts.laundryFeatures,resoFacts.levels,resoFacts.listingId,resoFacts.lotFeatures,resoFacts.lotSize,resoFacts.mainLevelBathrooms,resoFacts.mainLevelBedrooms,resoFacts.marketingType,resoFacts.middleOrJuniorSchool,resoFacts.middleOrJuniorSchoolDistrict,resoFacts.municipality,resoFacts.numberOfUnitsInCommunity,resoFacts.offerReviewDate,resoFacts.onMarketDate,resoFacts.openParkingCapacity,resoFacts.otherEquipment,resoFacts.otherFacts,resoFacts.otherParking,resoFacts.ownershipType,resoFacts.parkingCapacity,resoFacts.parkingFeatures,resoFacts.patioAndPorchFeatures,resoFacts.poolFeatures,resoFacts.pricePerSquareFoot,resoFacts.roadSurfaceType,resoFacts.roofType,resoFacts.rooms,resoFacts.securityFeatures,resoFacts.sewer,resoFacts.spaFeatures,resoFacts.specialListingConditions,resoFacts.stories,resoFacts.storiesTotal,resoFacts.subdivisionName,resoFacts.totalActualRent,resoFacts.utilities,resoFacts.view,resoFacts.waterSource,resoFacts.waterBodyName,resoFacts.waterfrontFeatures,resoFacts.waterView,resoFacts.waterViewYN,resoFacts.windowFeatures,resoFacts.yearBuilt,resoFacts.zoning,resoFacts.zoningDescription,resoFacts.aboveGradeFinishedArea,resoFacts.additionalParcelsDescription,resoFacts.architecturalStyle,resoFacts.belowGradeFinishedArea,resoFacts.builderModel,resoFacts.builderName,resoFacts.buildingArea,resoFacts.buildingAreaSource,resoFacts.buildingFeatures,resoFacts.constructionMaterials,resoFacts.exteriorFeatures,resoFacts.foundationDetails,resoFacts.frontageLength,resoFacts.frontageType,resoFacts.hasAdditionalParcels,resoFacts.hasPetsAllowed,resoFacts.hasRentControl,resoFacts.hasHomeWarranty,resoFacts.inclusions,resoFacts.incomeIncludes,resoFacts.isNewConstruction,resoFacts.listingTerms,resoFacts.livingAreaRange,resoFacts.livingAreaRangeUnits,resoFacts.livingArea,resoFacts.lotSizeDimensions,resoFacts.numberOfUnitsVacant,resoFacts.otherStructures,resoFacts.ownership,resoFacts.parcelNumber,resoFacts.propertyCondition,resoFacts.propertySubType,resoFacts.structureType,resoFacts.topography,resoFacts.vegetation,resoFacts.woodedArea,resoFacts.yearBuiltEffective,resoFacts.virtualTour,resoFacts.elementarySchool,resoFacts.elementarySchoolDistrict,resoFacts.listAOR,attributionInfo.listingAgreement,attributionInfo.mlsName,attributionInfo.agentEmail,attributionInfo.agentLicenseNumber,attributionInfo.agentName,attributionInfo.agentPhoneNumber,attributionInfo.attributionTitle,attributionInfo.brokerName,attributionInfo.brokerPhoneNumber,attributionInfo.buyerAgentMemberStateLicense,attributionInfo.buyerAgentName,attributionInfo.buyerBrokerageName,attributionInfo.coAgentLicenseNumber,attributionInfo.coAgentName,attributionInfo.coAgentNumber,attributionInfo.lastChecked,attributionInfo.lastUpdated,attributionInfo.listingOffices,attributionInfo.listingAgents,attributionInfo.mlsDisclaimer,attributionInfo.mlsId,attributionInfo.providerLogo,attributionInfo.infoString3,attributionInfo.infoString5,attributionInfo.infoString10,attributionInfo.infoString16,attributionInfo.trueStatus,homeRecommendations.blendedRecs,homeRecommendations.displayShort,parentRegion.name,listingMetadata.mustAttributeOfficeNameBeforeAgentName,listingMetadata.mustDisplayAttributionListAgentEmail,listingMetadata.mustDisplayAttributionListAgentPhone,listingMetadata.mustDisplayAttributionListingOfficePhone,listingMetadata.mustDisplayDisclaimerBelowAttribution,listingMetadata.mustHighlightAgentName,listingMetadata.mustHighlightListOfficeName,listingMetadata.mustMakeListingAgentContactable,listingMetadata.isAdsRestricted,listingMetadata.FlexibleLayoutAB,listingMetadata.FlexibleLayoutB,listingMetadata.FlexibleLayoutC,listingMetadata.FlexibleLayoutD,listingMetadata.FlexibleLayoutE,listingMetadata.FlexibleLayoutF,listingMetadata.FlexibleLayoutG,listingMetadata.FlexibleLayoutH,listingMetadata.FlexibleLayoutI,listingMetadata.FlexibleLayoutJ,listingMetadata.FlexibleLayoutK,listingMetadata.FlexibleLayoutL,listingMetadata.FlexibleLayoutM,listingMetadata.FlexibleLayoutN,listingMetadata.FlexibleLayoutO,listingMetadata.FlexibleLayoutP,listingMetadata.FlexibleLayoutQ,listingMetadata.FlexibleLayoutR,listingMetadata.FlexibleLayoutS,listingMetadata.FlexibleLayoutT,listingMetadata.FlexibleLayoutU,listingMetadata.FlexibleLayoutV,listingMetadata.FlexibleLayoutW,listingMetadata.FlexibleLayoutX,listingMetadata.FlexibleLayoutY,listingMetadata.FlexibleLayoutZ,listingMetadata.FlexibleLayoutAA,listingMetadata.passwordRequiredForZestimateMarketAnalysis,listingMetadata.canShowAutomatedValuationDisplay,listingMetadata.canShowTaxHistory,listingMetadata.canShowPriceHistory,listingMetadata.canShowUserGeneratedContent,listingMetadata.hidePriceAdjustmentFlexField,listingMetadata.canCommingleComparables,listingMetadata.canShowComparables,listingMetadata.isSuperTrafficOptimized,listingMetadata.mustDisplayFeedLogoInContactBox,listingMetadata.canShowCroppedPhotos,listingMetadata.canShowNonIDXMedia,listingMetadata.canShowOnMap,listingMetadata.comminglingCategory,listingMetadata.mustHighlightMlsId,listingMetadata.mustHighlightMlsStatus,listingMetadata.mustHighlightMarketingType,listingMetadata.canShowZillowLogoInHeader,listingMetadata.canShowPrequalifiedLinkInChip,listingMetadata.comminglingCategoryIsRulesApplicable,mortgageRates.fifteenYearFixedRate,mortgageRates.thirtyYearFixedRate,mortgageRates.arm5Rate,tourEligibility.isPropertyTourEligible,tourEligibility.propertyTourOptions.isFinal,tourEligibility.propertyTourOptions.tourAvailability,tourEligibility.propertyTourOptions.tourType,contactFormRenderData.data.agent_module.agent_reason,contactFormRenderData.data.agent_module.badge_type,contactFormRenderData.data.agent_module.business_name,contactFormRenderData.data.agent_module.display_name,contactFormRenderData.data.agent_module.encoded_zuid,contactFormRenderData.data.agent_module.first_name,contactFormRenderData.data.agent_module.image_data.height,contactFormRenderData.data.agent_module.image_data.url,contactFormRenderData.data.agent_module.image_data.width,contactFormRenderData.data.agent_module.phone,contactFormRenderData.data.agent_module.profile_url,contactFormRenderData.data.agent_module.rating_average,contactFormRenderData.data.agent_module.recent_sales,contactFormRenderData.data.agent_module.review_count,contactFormRenderData.data.agent_module.reviews_url,contactFormRenderData.data.agent_module.services_offered,contactFormRenderData.data.agent_module.write_review_url,contactFormRenderData.data.agent_module.zpro,contactFormRenderData.data.authentication.hmac,contactFormRenderData.data.authentication.request_id,contactFormRenderData.data.brokerage_info_must_be_shown,contactFormRenderData.data.contact_button_text,contactFormRenderData.data.contact_recipients,contactFormRenderData.data.cv_27.bal_checkboxes,contactFormRenderData.data.cv_27.brokerage_product,contactFormRenderData.data.cv_27.field_flags,contactFormRenderData.data.cv_27.form_identifier,contactFormRenderData.data.cv_27.mortgage_flags,contactFormRenderData.data.desktop_phone_number,contactFormRenderData.data.display_options.is_opaque_eligible,contactFormRenderData.data.displayed_agents,contactFormRenderData.data.displayed_lenders,contactFormRenderData.data.fallback_form.contact_recipients,contactFormRenderData.data.fallback_form.cv_27.bal_checkboxes,contactFormRenderData.data.fallback_form.cv_27.brokerage_product,contactFormRenderData.data.fallback_form.cv_27.field_flags,contactFormRenderData.data.fallback_form.cv_27.form_identifier,contactFormRenderData.data.fallback_form.cv_27.mortgage_flags,contactFormRenderData.data.fallback_form.footers,contactFormRenderData.data.fallback_form.hidden_fields,contactFormRenderData.data.fallback_form.subtitle,contactFormRenderData.data.fallback_form.title,contactFormRenderData.data.fallback_form.tour_eligible,contactFormRenderData.data.fallback_form.variant,contactFormRenderData.data.hidden_fields,contactFormRenderData.data.hide_textarea,contactFormRenderData.data.info_box_visible,contactFormRenderData.data.keller_williams,contactFormRenderData.data.lender_details.preapproval.checked,contactFormRenderData.data.lender_details.preapproval.label,contactFormRenderData.data.lender_details.preapproval.message_when_checked,contactFormRenderData.data.lender_details.preapproval_info.property_value,contactFormRenderData.data.lender_details.preapproval_info.state_abbr,contactFormRenderData.data.lender_details.preapproval_info.zipcode,contactFormRenderData.data.listing.direct_connect.tour_eligible,contactFormRenderData.data.listing.one_advisor,contactFormRenderData.data.listing.supports_unselected_leads,contactFormRenderData.data.opaque_la,contactFormRenderData.data.pixel_id,contactFormRenderData.data.pixel_url,contactFormRenderData.data.premier_agent_preferred_property,contactFormRenderData.data.region_phone_number.areacode,contactFormRenderData.data.region_phone_number.number,contactFormRenderData.data.region_phone_number.prefix,contactFormRenderData.data.request_trace.xpi,contactFormRenderData.data.request_trace.xsi,contactFormRenderData.data.request_trace.xti,contactFormRenderData.data.tcpa,contactFormRenderData.data.text_area.name,contactFormRenderData.data.text_area.value,contactFormRenderData.data.text_fields,contactFormRenderData.data.title,contactFormRenderData.data.tour_config.useFoundation,contactFormRenderData.data.tour_eligible,contactFormRenderData.data.variant,ZoDsFsUpsellTop.display,ZoDsFsUpsellTop.displayCategory,ZoDsFsUpsellTop.displayAttributes.leadType,ZoDsFsUpsellTop.treatment,ZoDsFsUpsellTop.surfaceId,ZoDsFsUpsellTop.placementId,ZoDsFsUpsellTop.reason,onsiteMessage.eventId,onsiteMessage.messages,foreclosureTypes.isBankOwned,foreclosureTypes.isForeclosedNFS,foreclosureTypes.isPreforeclosure,foreclosureTypes.isAnyForeclosure,foreclosureTypes.wasNonRetailAuction,foreclosureTypes.wasForeclosed,foreclosureTypes.wasREO,foreclosureTypes.wasDefault,staticMap.sources,listingSubType.isFSBA,listingSubType.isFSBO,listingSubType.isPending,listingSubType.isNewHome,listingSubType.isForeclosure,listingSubType.isBankOwned,listingSubType.isForAuction,listingSubType.isOpenHouse,listingSubType.isComingSoon,postingContact.name,postingContact.photo,vrModel.vrModelGuid,vrModel.revisionId,thirdPartyVirtualTour.externalUrl,thirdPartyVirtualTour.lightboxUrl,thirdPartyVirtualTour.staticUrl,thirdPartyVirtualTour.providerKey,thirdPartyVirtualTour.approved,topNavJson.topnav.json.logo.text,topNavJson.topnav.json.logo.href,topNavJson.topnav.json.main.sections,topNavJson.topnav.json.agent,topNavJson.topnav.json.marketing.sections,topNavJson.topnav.json.regLogin.sections,topNavJson.topnav.json.help.sections,topNavJson.topnav.json.common.home.text,topNavJson.topnav.json.common.home.href,topNavJson.topnav.json.common.advertise.text,topNavJson.topnav.json.common.advertise.href,topNavJson.topnav.json.common.login.text,topNavJson.topnav.json.common.login.href,topNavJson.topnav.json.common.register.text,topNavJson.topnav.json.common.register.href,topNavJson.core.js,formattedChip.location,selfTour.hasSelfTour

In [ ]:
print("Street address:", df_prop["streetAddress"].iloc[0])
print("City:", df_prop["city"].iloc[0])
print("State:", df_prop["state"].iloc[0])
print("Home status:", df_prop["homeStatus"].iloc[0])
print("Bedrooms:", df_prop["bedrooms"].iloc[0])
print("Bathrooms:", df_prop["bathrooms"].iloc[0])
print("Year built:", df_prop["yearBuilt"].iloc[0])
print("Zestimate: ${:,}".format(df_prop["zestimate"].iloc[0]))
print("Rent zestimate: ${:,}".format(df_prop["rentZestimate"].iloc[0]))
print("Description:")
df_prop["description"].iloc[0]

Street address: 3611 Potter St
City: Tampa
State: FL
Home status: FOR_SALE
Bedrooms: 3
Bathrooms: 2
Year built: 2020
Zestimate: $339,553
Rent zestimate: $2,414
Description:

'WOW! What an amazing NEW BUILD with 3 bedrooms, 2 bathrooms, 1 car garage, fully fenced backyard and an incredible kitchen. Fall in love with the gorgeous landscaping in your front yard and a front porch with exterior lighting. As soon as you go inside immediately cherish the openness and TILED great room with your living room to your right, kitchen in the middle including GRANITE COUNTERTOPS, real wood cabinets, WALK-IN PANTRY with wire shelving racks and STAINLESS STEEL APPLIANCES. As you go farther inside, to your left you can find the TILED dining room with BLINDS and a new light fixture. Following the TILE FLOOR into the hallway on the right appreciate your washer and dryer in a closet, tucked away until it’s laundry day. As you keep going through the hallway you can find the CARPETED master bedroom with a WALK IN CLOSET, blinds and on the side is your TILED master bathroom with DUAL SINKS, granite countertops, real wood cabinets, and a stand up shower. As you exit the master bedroom straight ahead you can find the other TILED bathroom including granite countertops, real wood cabinets, and a tub with shower. Adjacent to the bathroom you can find two CARPETED bedrooms with blinds, and two closet doors. Some additional features include NO HOA, windows are double insulated, hybrid hot water heater, and a security system. If you like to be outdoors you’re in luck you can find multiple parks nearby, McKay Bay, Hillsborough Bay, Lowry Park, Tampa Riverwalk, and so much more! Even if being outside isn’t for you there’s lots to do indoors close by including The Florida Aquarium, several museums, International mall and other malls, bowling and tons more! Also some roads close by for quick commute include the Suncoast, US-41, I-4, and the Selmon Expressway.'

#### Comparables

In [ ]:
# view comparables
df_c = pd.DataFrame(df_prop["comps"].iloc[0])
df_c

,zpid,miniCardPhotos,price,currency,bedrooms,bathrooms,livingArea,livingAreaValue,livingAreaUnits,livingAreaUnitsShort,listingMetadata,lotSize,lotAreaValue,lotAreaUnits,address,formattedChip,latitude,longitude,homeStatus,homeType,hdpUrl,listing_sub_type,providerListingID,attributionInfo,isPremierBuilder,state,isZillowOwned,newConstructionType
0,45108843,[{'url': 'https://photos.zillowstatic.com/fp/d...,325000,USD,3,1,1064,1064,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},3500,3500.000000,Square Feet,"{'streetAddress': '1801 E 18th Ave', 'city': '...",{'location': [{'fullValue': '1801 E 18th Ave'}...,27.968065,-82.438710,FOR_SALE,SINGLE_FAMILY,/homedetails/1801-E-18th-Ave-Tampa-FL-33605/45...,"{'is_newHome': False, 'is_forAuction': False, ...",None,"{'mlsId': 'T3430530', 'mlsName': None, 'provid...",False,FL,False,None
1,45100317,[{'url': 'https://photos.zillowstatic.com/fp/2...,394995,USD,3,3,1523,1523,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},2450,2450.000000,Square Feet,"{'streetAddress': '3618 N 25th St', 'city': 'T...","{'location': [{'fullValue': '3618 N 25th St'},...",27.977478,-82.431564,FOR_SALE,SINGLE_FAMILY,/homedetails/3618-N-25th-St-Tampa-FL-33605/451...,"{'is_newHome': True, 'is_forAuction': False, '...",None,"{'mlsId': 'T3429831', 'mlsName': None, 'provid...",False,FL,False,BUILDER_SPEC
2,45108732,[{'url': 'https://photos.zillowstatic.com/fp/f...,329999,USD,3,2,1092,1092,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},30491,0.700000,Acres,"{'streetAddress': '2904 Sanchez St', 'city': '...",{'location': [{'fullValue': '2904 Sanchez St'}...,27.968900,-82.442340,FOR_SALE,SINGLE_FAMILY,/homedetails/2904-Sanchez-St-Tampa-FL-33605/45...,"{'is_newHome': False, 'is_forAuction': False, ...",None,"{'mlsId': '821464', 'mlsName': None, 'provider...",False,FL,False,None
3,45099808,[{'url': 'https://photos.zillowstatic.com/fp/4...,299995,USD,3,2,1396,1396,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},12675,0.290978,Acres,"{'streetAddress': '3716 N 35th St', 'city': 'T...","{'location': [{'fullValue': '3716 N 35th St'},...",27.979225,-82.421130,FOR_SALE,SINGLE_FAMILY,/homedetails/3716-N-35th-St-Tampa-FL-33610/450...,"{'is_newHome': False, 'is_forAuction': False, ...",None,"{'mlsId': 'T3430083', 'mlsName': None, 'provid...",False,FL,False,None
4,2059031409,[{'url': 'https://photos.zillowstatic.com/fp/6...,419999,USD,3,2,1607,1607,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},5200,5200.000000,Square Feet,"{'streetAddress': '2803 N 33rd St', 'city': 'T...","{'location': [{'fullValue': '2803 N 33rd St'},...",27.968510,-82.423010,FOR_SALE,SINGLE_FAMILY,/homedetails/2803-N-33rd-St-Tampa-FL-33605/205...,"{'is_newHome': True, 'is_forAuction': False, '...",None,"{'mlsId': 'U8191744', 'mlsName': None, 'provid...",False,FL,False,BUILDER_SPEC
5,45082438,[{'url': 'https://photos.zillowstatic.com/fp/7...,339900,USD,3,2,1456,1456,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},11100,0.254821,Acres,"{'streetAddress': '1608 E Sitka St', 'city': '...",{'location': [{'fullValue': '1608 E Sitka St'}...,28.021452,-82.441956,FOR_SALE,SINGLE_FAMILY,/homedetails/1608-E-Sitka-St-Tampa-FL-33604/45...,"{'is_newHome': False, 'is_forAuction': False, ...",None,"{'mlsId': 'T3426989', 'mlsName': None, 'provid...",False,FL,False,None
6,45108845,[{'url': 'https://photos.zillowstatic.com/fp/6...,345000,USD,3,2,1187,1187,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},5300,5300.000000,Square Feet,"{'streetAddress': '1822 E 17th Ave', 'city': '...",{'location': [{'fullValue': '1822 E 17th Ave'}...,27.967752,-82.438150,FOR_SALE,SINGLE_FAMILY,/homedetails/1822-E-17th-Ave-Tampa-FL-33605/45...,"{'is_newHome': False, 'is_forAuction': False, ...",None,"{'mlsId': 'T3427190', 'mlsName': None, 'provid...",False,FL,False,None
7,45099406,[{'url': 'https://photos.zillowstatic.com/fp/f...,369000,USD,3,2,1858,1858,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},10400,10400.000000,Square Feet,"{'streetAddress': '3513 N 10th St', 'city': 'T...","{'location': [{'fullValue': '3513 N 10th St'},...",27.976995,-82.449180,FOR_SALE,SINGLE_FAMILY,/homedetails/3513-N-10th-St-Tampa-FL-33605/450...,"{'is_newHome': False, 'is_forAuction': False, ...",None,"{'mlsId': 'T3418765', 'mlsName': None, 'provid...",False,FL,False,None
8,45093593,[{'url': 'https://photos.zillowstatic.com/fp/e...,350000,USD,2,1,1040,1040,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},5100,5100.000000,Square Feet,"{'streetAddress': '204 W Chelsea St', 'city': ...",{'location': [{'fullValue': '204 W Chelsea St'...,27.984964,-82.461300,FOR_SALE,SINGLE_FAMILY,/homedetails/204-W-Chelsea-St-Tampa-FL-33603/4...,"{'is_newHome': False, 'is_forAuction': False, ...",None,"{'mlsId': 'T3430342', 'mlsName': None, 'provid...",False,FL,False,None
9,68576588,[{'url': 'https://photos.zillowstatic.com/fp/b...,359900,USD,3,2,1200,1200,Square Feet,sqft,{'comminglingCategoryIsRulesApplicable': True},5750,5750.000000,Square Feet,"{'streetAddress': '2908 12th St', 'city': 'Tam...","{'location': [{'fullValue': '2908 12th St'}, {...",27.969185,-82.447260,FOR_SALE,SINGLE_FAMILY,/homedetails/2908-12th-St-Tampa-FL-33605/68576...,"{'is_newHome': False, 'is_forAuction': False, ...",None,"{'mlsId': 'T3417938', 'mlsName': None, 'provid...",False,FL,False,None

#### Tax History

In [ ]:
# view tax history
df_tax_hist = pd.DataFrame(df_prop["taxHistory"].iloc[0])
df_tax_hist

             time  taxPaid  taxIncreaseRate  value  valueIncreaseRate
0   1614257548865   700.43         1.694998  35532           2.991014
1   1582635148865   259.90         0.029225   8903           0.099951
2   1551099148865   252.52         0.000000   8094          -0.509365
3   1519563148865   252.52         0.212290  16497           1.166667
4   1488027148865   208.30         0.450759   7614           0.252097
5   1456404748865   143.58         0.065055   6081           0.100036
6   1424868748865   134.81         0.212975   5528           0.100100
7   1393332748865   111.14         0.000000   5025           0.100044
8   1361796748865   111.14         0.129357   4568           0.000000
9   1330174348865    98.41         0.031660   4568           0.033952
10  1298638348865    95.39        -0.194613   4418          -0.199928
11  1267102348865   118.44        -0.689370   5522          -0.687528
12  1235566348865   381.29        -0.387466  17672          -0.384615
13  1203943948865   622.48        -0.060393  28717          -0.071429
14  1172407948865   662.49         0.279605  30926           0.400000
15  1140871948865   517.73         0.617754  22090           0.666667
16  1109335948865   320.03         0.000000  13254           0.500000
17  1077713548865      NaN         0.000000   8836           0.428618
18  1046177548865      NaN         0.000000   6185           0.000000
19  1014641548865      NaN         0.000000   6185          -0.020896
20   983105548865      NaN         0.000000   6317           0.000000
21   951483148865      NaN         0.000000   6317           0.000000

#### Price History

In [ ]:
# view price history
df_price_hist = pd.DataFrame(df_prop["priceHistory"].iloc[0])
df_price_hist

,date,time,price,pricePerSquareFoot,priceChangeRate,event,source,buyerAgent,sellerAgent,showCountyLink,postingIsRental,attributeSource
0,2023-02-04,1675468800000,350000,215,-0.041096,Price change,Stellar MLS / MFRMLS,None,None,False,False,"{'infoString1': 'T3424788', 'infoString2': 'St..."
1,2023-01-27,1674777600000,365000,224,0.383362,Listed for sale,Stellar MLS / MFRMLS,None,None,False,False,"{'infoString1': 'T3424788', 'infoString2': 'St..."
2,2023-01-02,1672617600000,2400,1,0.000000,Listing removed,HotPads,None,None,False,True,{'infoString1': '8da539eb3daa58a1532a386a012f2...
3,2022-12-05,1670198400000,2400,1,0.200000,Listed for rent,Zillow Rental Manager,None,None,False,True,"{'infoString1': None, 'infoString2': 'Zillow R..."
4,2021-12-16,1639612800000,2000,1,0.000000,Listing removed,Zillow Rental Network Premium,None,None,False,True,"{'infoString1': None, 'infoString2': 'Zillow R..."
5,2021-12-14,1639440000000,2000,1,-0.047619,Price change,Zillow Rental Network Premium,None,None,False,True,"{'infoString1': None, 'infoString2': 'Zillow R..."
6,2021-12-06,1638748800000,2100,1,-0.045455,Listed for rent,Zillow Rental Network Premium,None,None,False,True,"{'infoString1': None, 'infoString2': 'Zillow R..."
7,2021-10-15,1634256000000,2200,1,0.000000,Listing removed,Zillow Rental Network Premium,None,None,False,True,"{'infoString1': None, 'infoString2': 'Zillow R..."
8,2021-09-30,1632960000000,2200,1,0.000000,Listed for rent,Zillow Rental Network Premium,None,None,False,True,"{'infoString1': None, 'infoString2': 'Zillow R..."
9,2021-05-25,1621900800000,263850,162,0.000474,Sold,Stellar MLS / MFRMLS,{'photo': {'url': 'https://photos.zillowstatic...,None,False,False,"{'infoString1': 'T3270295', 'infoString2': 'St..."
10,2021-04-09,1617926400000,263725,162,0.000000,Pending sale,Stellar MLS / MFRMLS,None,None,False,False,"{'infoString1': 'T3270295', 'infoString2': 'St..."
11,2020-10-12,1602460800000,263725,162,0.000000,Listed for sale,DOMAIN REALTY LLC,None,None,False,False,"{'infoString1': None, 'infoString2': 'DOMAIN R..."

### <font color="green">4. Locate ZPID by Address</font>

In [ ]:
street = "12315 N Oakleaf Ave"
city = "Tampa"
state = "FL"
# zip_code = "33612" #[optional]

zpid_response = get_zpid(api_key, street, city, state, zip_code=None)

In [ ]:
zpid_response.json()["is_success"]

True

In [ ]:
# view response, top possible zpids
pd.DataFrame(zpid_response.json()["data"])

       zpid                                                url
0  44905318  https://www.zillow.com/homedetails/12315-N-Oak...
1  44905319  https://www.zillow.com/homedetails/12319-N-Oak...
2  44905317  https://www.zillow.com/homedetails/12311-N-Oak...
3  44905324  https://www.zillow.com/homedetails/12315-Woodl...
4  44905320  https://www.zillow.com/homedetails/1714-Round-...

In [ ]:
print("Zpid:", zpid_response.json()["data"][0]["zpid"])

Zpid: 44905318

### <font color="green">5. FSBO (For Sale By Owner) Listings</font>

In [ ]:
fsbo_url = "https://www.zillow.com/tampa-fl/?searchQueryState=%7B%22usersSearchTerm%22%3A%22Tampa%2C%20FL%22%2C%22mapBounds%22%3A%7B%22west%22%3A-82.85425150830079%2C%22east%22%3A-82.05430949169923%2C%22south%22%3A27.749100096033082%2C%22north%22%3A28.239597518118032%7D%2C%22regionSelection%22%3A%5B%7B%22regionId%22%3A41176%2C%22regionType%22%3A6%7D%5D%2C%22isMapVisible%22%3Atrue%2C%22filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22globalrelevanceex%22%7D%2C%22ah%22%3A%7B%22value%22%3Atrue%7D%2C%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22tow%22%3A%7B%22value%22%3Afalse%7D%2C%22mf%22%3A%7B%22value%22%3Afalse%7D%2C%22con%22%3A%7B%22value%22%3Afalse%7D%2C%22apco%22%3A%7B%22value%22%3Afalse%7D%2C%22land%22%3A%7B%22value%22%3Afalse%7D%2C%22apa%22%3A%7B%22value%22%3Afalse%7D%2C%22manu%22%3A%7B%22value%22%3Afalse%7D%2C%22price%22%3A%7B%22max%22%3A1000000%7D%2C%22mp%22%3A%7B%22max%22%3A5155%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A11%2C%22category%22%3A%22cat2%22%2C%22pagination%22%3A%7B%7D%7D"

In [ ]:
fspo_response = get_listings(api_key, fsbo_url)

In [ ]:
# view count of properies returned in request
num_of_properties = fspo_response.json()["data"]["categoryTotals"]["cat2"]["totalResultCount"]
print("Count of properties:", num_of_properties)

Count of properties: 20

In [ ]:
# view all listings
df_fsbo_listings = pd.json_normalize(fspo_response.json()["data"]["cat2"]["searchResults"]["mapResults"])
print("Number of rows:", len(df_fsbo_listings))
print("Number of columns:", len(df_fsbo_listings.columns))
df_fsbo_listings

Number of rows: 20
Number of columns: 67

,zpid,price,priceLabel,beds,baths,area,statusType,statusText,isFavorite,isUserClaimingOwner,isUserConfirmedClaim,imgSrc,hasImage,visited,listingType,variableData,shouldShowZestimateAsPrice,detailUrl,pgapt,sgapt,has3DModel,hasVideo,isHomeRec,address,hasAdditionalAttributions,isFeaturedListing,availabilityDate,latLong.latitude,latLong.longitude,hdpData.homeInfo.zpid,hdpData.homeInfo.zipcode,hdpData.homeInfo.city,hdpData.homeInfo.state,hdpData.homeInfo.latitude,hdpData.homeInfo.longitude,hdpData.homeInfo.price,hdpData.homeInfo.bathrooms,hdpData.homeInfo.bedrooms,hdpData.homeInfo.livingArea,hdpData.homeInfo.homeType,hdpData.homeInfo.homeStatus,hdpData.homeInfo.daysOnZillow,hdpData.homeInfo.isFeatured,hdpData.homeInfo.shouldHighlight,hdpData.homeInfo.rentZestimate,hdpData.homeInfo.listing_sub_type.is_FSBO,hdpData.homeInfo.isUnmappable,hdpData.homeInfo.isPreforeclosureAuction,hdpData.homeInfo.homeStatusForHDP,hdpData.homeInfo.priceForHDP,hdpData.homeInfo.isNonOwnerOccupied,hdpData.homeInfo.isPremierBuilder,hdpData.homeInfo.isZillowOwned,hdpData.homeInfo.currency,hdpData.homeInfo.country,hdpData.homeInfo.lotAreaValue,hdpData.homeInfo.lotAreaUnit,hdpData.homeInfo.zestimate,hdpData.homeInfo.taxAssessedValue,variableData.type,variableData.text,variableData.data.isFresh,hdpData.homeInfo.datePriceChanged,hdpData.homeInfo.priceReduction,hdpData.homeInfo.priceChange,hdpData.homeInfo.videoCount,hdpData.homeInfo.unit
0,2076754227,"$265,000",$265K,2,3.0,1568,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/a2d81866c8e...,True,False,,NaN,False,/homedetails/3747-Winward-Lakes-Dr-Tampa-FL-33...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.876034,-82.505650,2076754227,33611,Tampa,FL,27.876034,-82.505650,265000.0,3.0,2.0,1568.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2799,True,False,False,FOR_SALE,265000.0,True,False,False,USD,USA,4000.000000,sqft,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,45092182,"$515,000",$515K,3,2.0,1655,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/2c2a6744073...,True,False,,NaN,False,/homedetails/5905-N-Suwanee-Ave-Tampa-FL-33604...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,28.001055,-82.458140,45092182,33604,Tampa,FL,28.001055,-82.458140,515000.0,2.0,3.0,1655.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2833,True,False,False,FOR_SALE,515000.0,True,False,False,USD,USA,6969.000000,sqft,383600.0,239827.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2138562422,"$360,000",$360K,3,3.0,1526,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/3108eba6a12...,True,False,,NaN,False,/homedetails/20112-Heron-Crossing-Dr-Tampa-FL-...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,28.159235,-82.387210,2138562422,33647,Tampa,FL,28.159235,-82.387210,360000.0,3.0,3.0,1526.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2199,True,False,False,FOR_SALE,360000.0,True,False,False,USD,USA,3850.000000,sqft,349500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,45081822,"$435,000",$435K,4,4.0,2266,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/bb7bfd2dd3c...,True,False,,NaN,False,/homedetails/2014-E-Broad-St-Tampa-FL-33610/45...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,28.016432,-82.435326,45081822,33610,Tampa,FL,28.016432,-82.435326,435000.0,4.0,4.0,2266.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2709,True,False,False,FOR_SALE,435000.0,True,False,False,USD,USA,6337.000000,sqft,434600.0,232709.0,TIME_ON_INFO,8 hours ago,False,NaN,NaN,NaN,NaN,NaN
4,45037717,"$304,900",$305K,3,2.0,1161,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/9f719807213...,True,False,,NaN,False,/homedetails/1504-W-Hollywood-St-Tampa-FL-3360...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,28.019226,-82.474960,45037717,33604,Tampa,FL,28.019226,-82.474960,304900.0,2.0,3.0,1161.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,1997,True,False,False,FOR_SALE,304900.0,True,False,False,USD,USA,8712.000000,sqft,285500.0,137868.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,60618071,"$625,000",$625K,4,3.0,2605,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/f2ba5ba9c50...,True,False,,NaN,False,/homedetails/17312-Chenango-Ln-Tampa-FL-33647/...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,28.128172,-82.384895,60618071,33647,Tampa,FL,28.128172,-82.384895,625000.0,3.0,4.0,2605.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,3494,True,False,False,FOR_SALE,625000.0,True,False,False,USD,USA,0.359986,acres,614800.0,364025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,45092695,"$279,900",$280K,2,1.0,864,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/f2bdcc17de4...,True,False,,NaN,False,/homedetails/816-E-Wilder-Ave-Tampa-FL-33603/4...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.992610,-82.451940,45092695,33603,Tampa,FL,27.992610,-82.451940,279900.0,1.0,2.0,864.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,1727,True,False,False,FOR_SALE,279900.0,True,False,False,USD,USA,6969.000000,sqft,258600.0,111213.0,PRICE_REDUCTION,"$15,000 (Feb 11)",NaN,1.676102e+12,"$15,000 (Feb 11)",-15000.0,NaN,NaN
7,45041202,"$550,000",$550K,4,2.0,2449,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/de9f4550d6b...,True,False,,NaN,False,/homedetails/2115-W-Dallas-Ave-Tampa-FL-33603/...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.988577,-82.481705,45041202,33603,Tampa,FL,27.988577,-82.481705,550000.0,2.0,4.0,2449.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2937,True,False,False,FOR_SALE,550000.0,True,False,False,USD,USA,0.261685,acres,522900.0,322281.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,44885527,"$300,000",$300K,2,2.0,934,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/86aa1137bf4...,True,False,,NaN,False,/homedetails/2720-Midtimes-Dr-Tampa-FL-33618/4...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,28.102764,-82.488120,44885527,33618,Tampa,FL,28.102764,-82.488120,300000.0,2.0,2.0,934.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,1663,True,False,False,FOR_SALE,300000.0,True,False,False,USD,USA,6534.000000,sqft,272200.0,156446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,45085863,"$350,000",$350K,3,3.0,1438,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/95f2f9aac8b...,True,False,,NaN,False,/homedetails/3906-E-Louisiana-Ave-Tampa-FL-336...,ForSale,For Sale By Owner,False,True,False,--,False,False,None,27.989887,-82.415560,45085863,33610,Tampa,FL,27.989887,-82.415560,350000.0,3.0,3.0,1438.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2075,True,False,False,FOR_SALE,350000.0,True,False,False,USD,USA,8258.000000,sqft,288700.0,184696.0,VIDEO_WALKTHROUGH,Video Walkthrough,NaN,NaN,NaN,NaN,1.0,NaN
10,45096441,"$485,000",$485K,2,2.0,1200,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/37eb64ad8da...,True,False,,NaN,False,/homedetails/43-Hamilton-Heath-Dr-Tampa-FL-336...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,28.018715,-82.449290,45096441,33604,Tampa,FL,28.018715,-82.449290,485000.0,2.0,2.0,1200.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,1900,True,False,False,FOR_SALE,485000.0,True,False,False,USD,USA,5662.000000,sqft,339800.0,186700.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,332364004,"$429,750",$430K,3,2.0,2080,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/9377df5078f...,True,False,,NaN,False,/homedetails/5026-W-Ingraham-St-Tampa-FL-33616...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.861937,-82.530815,332364004,33616,Tampa,FL,27.861937,-82.530815,429750.0,2.0,3.0,2080.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2496,True,False,False,FOR_SALE,429750.0,True,False,False,USD,USA,4791.000000,sqft,425500.0,242822.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,44962307,"$479,000",$479K,3,2.0,1996,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/37d494da39d...,True,False,,NaN,False,/homedetails/9325-Hampshire-Park-Dr-Tampa-FL-3...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,28.129007,-82.338460,44962307,33647,Tampa,FL,28.129007,-82.338460,479000.0,2.0,3.0,1996.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2499,True,False,False,FOR_SALE,479000.0,True,False,False,USD,USA,10454.000000,sqft,460100.0,258127.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,45101047,"$425,000",$425K,3,1.0,1548,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/f3b6ea3d37b...,True,False,,NaN,False,/homedetails/2702-W-Abdella-St-Tampa-FL-33607/...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.970207,-82.487130,45101047,33607,Tampa,FL,27.970207,-82.487130,425000.0,1.0,3.0,1548.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2665,True,False,False,FOR_SALE,425000.0,True,False,False,USD,USA,10018.000000,sqft,320100.0,201720.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,45041679,"$625,000",$625K,3,3.0,2281,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/2ec4ac90231...,True,False,,NaN,False,/homedetails/4604-Wishart-Blvd-Tampa-FL-33603/...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.984886,-82.481190,45041679,33603,Tampa,FL,27.984886,-82.481190,625000.0,3.0,3.0,2281.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,3085,True,False,False,FOR_SALE,625000.0,True,False,False,USD,USA,7300.000000,sqft,616500.0,394655.0,PRICE_REDUCTION,"$40,000 (Jan 9)",NaN,1.673251e+12,"$40,000 (Jan 9)",-40000.0,NaN,NaN
15,45056583,"$424,900",$425K,2,1.0,1060,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/d4ae69329db...,True,False,,NaN,False,/homedetails/3016-S-Manhattan-Ave-Tampa-FL-336...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.918673,-82.517630,45056583,33629,Tampa,FL,27.918673,-82.517630,424900.0,1.0,2.0,1060.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2411,True,False,False,FOR_SALE,424900.0,True,False,False,USD,USA,5000.000000,sqft,428500.0,208098.0,PRICE_REDUCTION,"$14,100 (Jan 11)",NaN,1.673424e+12,"$14,100 (Jan 11)",-14100.0,NaN,NaN
16,45070498,"$495,000",$495K,3,2.0,1244,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/44a6721a349...,True,False,,NaN,False,/homedetails/6718-S-Sheridan-Rd-Tampa-FL-33611...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.870771,-82.497480,45070498,33611,Tampa,FL,27.870771,-82.497480,495000.0,2.0,3.0,1244.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,2499,True,False,False,FOR_SALE,495000.0,True,False,False,USD,USA,6325.000000,sqft,392400.0,219785.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,45052705,"$685,000",$685K,3,2.0,1746,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/5a209ac9699...,True,False,,NaN,False,/homedetails/3918-W-Watrous-Ave-Tampa-FL-33629...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.931807,-82.509530,45052705,33629,Tampa,FL,27.931807,-82.509530,685000.0,2.0,3.0,1746.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,3913,True,False,False,FOR_SALE,685000.0,True,False,False,USD,USA,0.250000,acres,561800.0,342645.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2128448620,"$649,900",$650K,0,2.0,2762,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/933d9d49942...,True,False,,NaN,False,/homedetails/301-S-22nd-St-Tampa-FL-33605/2128...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.947040,-82.434920,2128448620,33605,Tampa,FL,27.947040,-82.434920,649900.0,2.0,0.0,2762.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,1635,True,False,False,FOR_SALE,649900.0,True,False,False,USD,USA,9147.000000,sqft,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2075221652,"$970,000",$970K,3,4.0,1868,FOR_SALE,For sale by owner,False,False,False,https://photos.zillowstatic.com/fp/fe24b0a63b1...,True,False,,NaN,False,/homedetails/204-S-Tampania-Ave-2-Tampa-FL-336...,ForSale,For Sale By Owner,False,False,False,--,False,False,None,27.943295,-82.486070,2075221652,33609,Tampa,FL,27.943295,-82.486070,970000.0,4.0,3.0,1868.0,SINGLE_FAMILY,FOR_SALE,-1,False,False,4142,True,False,False,FOR_SALE,970000.0,True,False,False,USD,USA,3223.000000,sqft,734900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,# 2

In [ ]:
# view price
px.box(df_fsbo_listings, x="hdpData.homeInfo.price", title="Sales Price Histogram")

#### <font color="purple">Get Owner Phone Number</font>

In [ ]:
# select a sample fspo property from the dataframe
fsbo_single_listing = "45081822" # zpid

In [ ]:
# get property detail
fsbo_prop_detail_response = get_property_detail(api_key, fsbo_single_listing)

# view property details
df_fsbo_prop = pd.json_normalize(fsbo_prop_detail_response.json()['data'])
print("Number of rows:", len(df_fsbo_prop))
print("Number of columns:", len(df_fsbo_prop.columns))
df_fsbo_prop

Number of rows: 1
Number of columns: 607

,listingDataSource,zpid,city,state,homeStatus,isListingClaimedByCurrentSignedInUser,isCurrentSignedInAgentResponsible,bedrooms,bathrooms,price,yearBuilt,streetAddress,zipcode,isCurrentSignedInUserVerifiedOwner,regionString,propertyUpdatePageLink,moveHomeMapLocationLink,propertyEventLogLink,editPropertyHistorylink,isRentalListingOffMarket,hdpUrl,nearbyCities,nearbyNeighborhoods,country,nearbyZipcodes,abbreviatedAddress,building,isUndisclosedAddress,boroughId,providerListingID,boroughSearchUrl,communityUrl,isPremierBuilder,isZillowOwned,homeType,currency,listPriceLow,livingArea,livingAreaValue,zestimate,newConstructionType,zestimateLowPercent,zestimateHighPercent,rentZestimate,restimateLowPercent,restimateHighPercent,schools,homeValues,nearbyHomes,countyFIPS,parcelId,taxHistory,priceHistory,comps,description,whatILove,contingentListingType,timeOnZillow,pageViewCount,favoriteCount,daysOnZillow,latitude,longitude,openHouseSchedule,desktopWebHdpImageLink,brokerageName,timeZone,pals,listingAccountUserId,homeInsights,sellingSoon,isIncomeRestricted,brokerId,ssid,monthlyHoaFee,propertyTaxRate,hiResImageLink,hdpTypeDimension,mlsid,propertyTypeDimension,mediumImageLink,enhancedBrokerImageUrl,responsivePhotos,buildingId,virtualTourUrl,hasApprovedThirdPartyVirtualTourUrl,photoCount,livingAreaUnits,lotSize,lotAreaValue,lotAreaUnits,postingProductType,marketingName,richMedia,cityId,stateId,zipPlusFour,numberOfUnitsTotal,foreclosureDefaultFilingDate,foreclosureAuctionFilingDate,foreclosureLoanDate,foreclosureLoanOriginator,foreclosureLoanAmount,foreclosurePriorSaleDate,foreclosurePriorSaleAmount,foreclosureBalanceReportingDate,foreclosurePastDueBalance,foreclosureUnpaidBalance,foreclosureAuctionTime,foreclosureAuctionDescription,foreclosureAuctionCity,foreclosureAuctionLocation,foreclosureDate,foreclosureAmount,foreclosingBank,foreclosureJudicialType,datePostedString,foreclosureMoreInfo,hasBadGeocode,streetViewMetadataUrlMediaWallLatLong,streetViewMetadataUrlMediaWallAddress,streetViewTileImageUrlMediumLatLong,streetViewTileImageUrlMediumAddress,streetViewServiceUrl,postingUrl,hasPublicVideo,primaryPublicVideo,richMediaVideos,photos,tourViewCount,listingAccount,listingFeedID,livingAreaUnitsShort,priceChange,priceChangeDate,priceChangeDateString,hideZestimate,comingSoonOnMarketDate,isPreforeclosureAuction,lastSoldPrice,isHousingConnector,responsivePhotosOriginalRatio,streetViewMetadataUrlMapLightboxAddress,thumb,isRecentStatusChange,isNonOwnerOccupied,county,isFeatured,rentalApplicationsAcceptedType,listingTypeDimension,featuredListingTypeDimension,brokerIdDimension,keystoneHomeStatus,pageUrlFragment,isRentalsLeadCapMet,isPaidMultiFamilyBrokerId,address.streetAddress,address.city,address.state,address.zipcode,address.neighborhood,address.community,address.subdivision,listing_sub_type.is_newHome,listing_sub_type.is_FSBO,listing_sub_type.is_FSBA,listing_sub_type.is_foreclosure,listing_sub_type.is_bankOwned,listing_sub_type.is_forAuction,listing_sub_type.is_comingSoon,listing_sub_type.is_pending,listing_sub_type.is_openHouse,citySearchUrl.text,citySearchUrl.path,zipcodeSearchUrl.path,apartmentsForRentInZipcodeSearchUrl.path,housesForRentInZipcodeSearchUrl.path,neighborhoodRegion.name,neighborhoodSearchUrl.path,stateSearchUrl.path,countySearchUrl.text,countySearchUrl.path,adTargets.aamgnrc1,adTargets.bd,adTargets.city,adTargets.proptp,adTargets.pid,adTargets.lot,adTargets.zestibuck,adTargets.listtp,adTargets.sqftrange,adTargets.price,adTargets.sqft,adTargets.state,adTargets.mlong,adTargets.cnty,adTargets.prange,adTargets.zip,adTargets.mlat,adTargets.zusr,adTargets.price_band,adTargets.yrblt,adTargets.zestimate,adTargets.tflag,adTargets.premieragent,adTargets.dma,adTargets.guid,adTargets.ssid,resoFacts.accessibilityFeatures,resoFacts.additionalFeeInfo,resoFacts.associationFee,resoFacts.associationAmenities,resoFacts.associationFee2,resoFacts.associationFeeIncludes,resoFacts.associationName,resoFacts.associationName2,resoFacts.associationPhone,resoFacts.associationPhone2,resoFacts.basementYN,resoFacts.buildingName,resoFacts.buyerAgencyCompensation,resoFacts.buyerAgencyCompensationType,resoFacts.appliances,resoFacts.atAGlanceFacts,resoFacts.attic,resoFacts.availabilityDate,resoFacts.basement,resoFacts.bathrooms,resoFacts.bathroomsFull,resoFacts.bathroomsHalf,resoFacts.bathroomsOneQuarter,resoFacts.bathroomsPartial,resoFacts.bathroomsThreeQuarter,resoFacts.bedrooms,resoFacts.bodyType,resoFacts.canRaiseHorses,resoFacts.carportParkingCapacity,resoFacts.cityRegion,resoFacts.commonWalls,resoFacts.communityFeatures,resoFacts.cooling,resoFacts.coveredParkingCapacity,resoFacts.cropsIncludedYN,resoFacts.developmentStatus,resoFacts.doorFeatures,resoFacts.electric,resoFacts.elevation,resoFacts.elevationUnits,resoFacts.entryLevel,resoFacts.entryLocation,resoFacts.exclusions,resoFacts.fencing,resoFacts.fireplaceFeatures,resoFacts.fireplaces,resoFacts.flooring,resoFacts.foundationArea,resoFacts.furnished,resoFacts.garageParkingCapacity,resoFacts.gas,resoFacts.greenBuildingVerificationType,resoFacts.greenEnergyEfficient,resoFacts.greenIndoorAirQuality,resoFacts.greenSustainability,resoFacts.greenWaterConservation,resoFacts.hasAssociation,resoFacts.hasAttachedGarage,resoFacts.hasAttachedProperty,resoFacts.hasCooling,resoFacts.hasCarport,resoFacts.hasElectricOnProperty,resoFacts.hasFireplace,resoFacts.hasGarage,resoFacts.hasHeating,resoFacts.hasLandLease,resoFacts.hasOpenParking,resoFacts.hasSpa,resoFacts.hasPrivatePool,resoFacts.hasView,resoFacts.hasWaterfrontView,resoFacts.heating,resoFacts.highSchool,resoFacts.highSchoolDistrict,resoFacts.hoaFee,resoFacts.homeType,resoFacts.horseAmenities,resoFacts.horseYN,resoFacts.interiorFeatures,resoFacts.irrigationWaterRightsAcres,resoFacts.irrigationWaterRightsYN,resoFacts.isSeniorCommunity,resoFacts.landLeaseAmount,resoFacts.landLeaseExpirationDate,resoFacts.laundryFeatures,resoFacts.levels,resoFacts.listingId,resoFacts.lotFeatures,resoFacts.lotSize,resoFacts.mainLevelBathrooms,resoFacts.mainLevelBedrooms,resoFacts.marketingType,resoFacts.middleOrJuniorSchool,resoFacts.middleOrJuniorSchoolDistrict,resoFacts.municipality,resoFacts.numberOfUnitsInCommunity,resoFacts.offerReviewDate,resoFacts.onMarketDate,resoFacts.openParkingCapacity,resoFacts.otherEquipment,resoFacts.otherFacts,resoFacts.otherParking,resoFacts.ownershipType,resoFacts.parkingCapacity,resoFacts.parkingFeatures,resoFacts.patioAndPorchFeatures,resoFacts.poolFeatures,resoFacts.pricePerSquareFoot,resoFacts.roadSurfaceType,resoFacts.roofType,resoFacts.rooms,resoFacts.securityFeatures,resoFacts.sewer,resoFacts.spaFeatures,resoFacts.specialListingConditions,resoFacts.stories,resoFacts.storiesTotal,resoFacts.subdivisionName,resoFacts.totalActualRent,resoFacts.utilities,resoFacts.view,resoFacts.waterSource,resoFacts.waterBodyName,resoFacts.waterfrontFeatures,resoFacts.waterView,resoFacts.waterViewYN,resoFacts.windowFeatures,resoFacts.yearBuilt,resoFacts.zoning,resoFacts.zoningDescription,resoFacts.aboveGradeFinishedArea,resoFacts.additionalParcelsDescription,resoFacts.architecturalStyle,resoFacts.belowGradeFinishedArea,resoFacts.builderModel,resoFacts.builderName,resoFacts.buildingArea,resoFacts.buildingAreaSource,resoFacts.buildingFeatures,resoFacts.constructionMaterials,resoFacts.exteriorFeatures,resoFacts.foundationDetails,resoFacts.frontageLength,resoFacts.frontageType,resoFacts.hasAdditionalParcels,resoFacts.hasPetsAllowed,resoFacts.hasRentControl,resoFacts.hasHomeWarranty,resoFacts.inclusions,resoFacts.incomeIncludes,resoFacts.isNewConstruction,resoFacts.listingTerms,resoFacts.livingAreaRange,resoFacts.livingAreaRangeUnits,resoFacts.livingArea,resoFacts.lotSizeDimensions,resoFacts.numberOfUnitsVacant,resoFacts.otherStructures,resoFacts.ownership,resoFacts.parcelNumber,resoFacts.propertyCondition,resoFacts.propertySubType,resoFacts.structureType,resoFacts.topography,resoFacts.vegetation,resoFacts.woodedArea,resoFacts.yearBuiltEffective,resoFacts.virtualTour,resoFacts.elementarySchool,resoFacts.elementarySchoolDistrict,resoFacts.listAOR,attributionInfo.listingAgreement,attributionInfo.mlsName,attributionInfo.agentEmail,attributionInfo.agentLicenseNumber,attributionInfo.agentName,attributionInfo.agentPhoneNumber,attributionInfo.attributionTitle,attributionInfo.brokerName,attributionInfo.brokerPhoneNumber,attributionInfo.buyerAgentMemberStateLicense,attributionInfo.buyerAgentName,attributionInfo.buyerBrokerageName,attributionInfo.coAgentLicenseNumber,attributionInfo.coAgentName,attributionInfo.coAgentNumber,attributionInfo.lastChecked,attributionInfo.lastUpdated,attributionInfo.listingOffices,attributionInfo.listingAgents,attributionInfo.mlsDisclaimer,attributionInfo.mlsId,attributionInfo.providerLogo,attributionInfo.infoString3,attributionInfo.infoString5,attributionInfo.infoString10,attributionInfo.infoString16,attributionInfo.trueStatus,homeRecommendations.blendedRecs,homeRecommendations.displayShort,parentRegion.name,listingMetadata.mustAttributeOfficeNameBeforeAgentName,listingMetadata.mustDisplayAttributionListAgentEmail,listingMetadata.mustDisplayAttributionListAgentPhone,listingMetadata.mustDisplayAttributionListingOfficePhone,listingMetadata.mustDisplayDisclaimerBelowAttribution,listingMetadata.mustHighlightAgentName,listingMetadata.mustHighlightListOfficeName,listingMetadata.mustMakeListingAgentContactable,listingMetadata.isAdsRestricted,listingMetadata.FlexibleLayoutAB,listingMetadata.FlexibleLayoutB,listingMetadata.FlexibleLayoutC,listingMetadata.FlexibleLayoutD,listingMetadata.FlexibleLayoutE,listingMetadata.FlexibleLayoutF,listingMetadata.FlexibleLayoutG,listingMetadata.FlexibleLayoutH,listingMetadata.FlexibleLayoutI,listingMetadata.FlexibleLayoutJ,listingMetadata.FlexibleLayoutK,listingMetadata.FlexibleLayoutL,listingMetadata.FlexibleLayoutM,listingMetadata.FlexibleLayoutN,listingMetadata.FlexibleLayoutO,listingMetadata.FlexibleLayoutP,listingMetadata.FlexibleLayoutQ,listingMetadata.FlexibleLayoutR,listingMetadata.FlexibleLayoutS,listingMetadata.FlexibleLayoutT,listingMetadata.FlexibleLayoutU,listingMetadata.FlexibleLayoutV,listingMetadata.FlexibleLayoutW,listingMetadata.FlexibleLayoutX,listingMetadata.FlexibleLayoutY,listingMetadata.FlexibleLayoutZ,listingMetadata.FlexibleLayoutAA,listingMetadata.passwordRequiredForZestimateMarketAnalysis,listingMetadata.canShowAutomatedValuationDisplay,listingMetadata.canShowTaxHistory,listingMetadata.canShowPriceHistory,listingMetadata.canShowUserGeneratedContent,listingMetadata.hidePriceAdjustmentFlexField,listingMetadata.canCommingleComparables,listingMetadata.canShowComparables,listingMetadata.isSuperTrafficOptimized,listingMetadata.mustDisplayFeedLogoInContactBox,listingMetadata.canShowCroppedPhotos,listingMetadata.canShowNonIDXMedia,listingMetadata.canShowOnMap,listingMetadata.comminglingCategory,listingMetadata.mustHighlightMlsId,listingMetadata.mustHighlightMlsStatus,listingMetadata.mustHighlightMarketingType,listingMetadata.canShowZillowLogoInHeader,listingMetadata.canShowPrequalifiedLinkInChip,listingMetadata.comminglingCategoryIsRulesApplicable,listingProvider.title,listingProvider.disclaimerText,listingProvider.enhancedVideoURL,listingProvider.enhancedDescriptionText,listingProvider.showLogos,listingProvider.logos,listingProvider.showNoContactInfoMessage,listingProvider.agentName,listingProvider.agentLicenseNumber,listingProvider.postingWebsiteURL,listingProvider.postingWebsiteLinkText,listingProvider.postingGroupName,listingProvider.sourceText,listingProvider.isZRMSourceText,mortgageRates.fifteenYearFixedRate,mortgageRates.thirtyYearFixedRate,mortgageRates.arm5Rate,tourEligibility.isPropertyTourEligible,tourEligibility.propertyTourOptions.isFinal,tourEligibility.propertyTourOptions.tourAvailability,tourEligibility.propertyTourOptions.tourType,contactFormRenderData.data.agent_module.agent_reason,contactFormRenderData.data.agent_module.display_name,contactFormRenderData.data.agent_module.encoded_zuid,contactFormRenderData.data.agent_module.first_name,contactFormRenderData.data.agent_module.image_data.height,contactFormRenderData.data.agent_module.image_data.url,contactFormRenderData.data.agent_module.image_data.width,contactFormRenderData.data.agent_module.phone.areacode,contactFormRenderData.data.agent_module.phone.number,contactFormRenderData.data.agent_module.phone.prefix,contactFormRenderData.data.authentication.hmac,contactFormRenderData.data.authentication.request_id,contactFormRenderData.data.brokerage_info_must_be_shown,contactFormRenderData.data.contact_button_text,contactFormRenderData.data.contact_recipients,contactFormRenderData.data.cv_27.bal_checkboxes,contactFormRenderData.data.cv_27.brokerage_product,contactFormRenderData.data.cv_27.field_flags,contactFormRenderData.data.cv_27.form_identifier,contactFormRenderData.data.cv_27.mortgage_flags,contactFormRenderData.data.desktop_phone_number,contactFormRenderData.data.display_options.is_opaque_eligible,contactFormRenderData.data.displayed_agents,contactFormRenderData.data.displayed_lenders,contactFormRenderData.data.fallback_form.contact_recipients,contactFormRenderData.data.fallback_form.cv_27.bal_checkboxes,contactFormRenderData.data.fallback_form.cv_27.brokerage_product,contactFormRenderData.data.fallback_form.cv_27.field_flags,contactFormRenderData.data.fallback_form.cv_27.form_identifier,contactFormRenderData.data.fallback_form.cv_27.mortgage_flags,contactFormRenderData.data.fallback_form.footers,contactFormRenderData.data.fallback_form.hidden_fields,contactFormRenderData.data.fallback_form.subtitle,contactFormRenderData.data.fallback_form.title,contactFormRenderData.data.fallback_form.tour_eligible,contactFormRenderData.data.fallback_form.variant,contactFormRenderData.data.hidden_fields,contactFormRenderData.data.hide_textarea,contactFormRenderData.data.info_box_visible,contactFormRenderData.data.keller_williams,contactFormRenderData.data.lender_details.preapproval.checked,contactFormRenderData.data.lender_details.preapproval.label,contactFormRenderData.data.lender_details.preapproval.message_when_checked,contactFormRenderData.data.lender_details.preapproval_info.property_value,contactFormRenderData.data.lender_details.preapproval_info.state_abbr,contactFormRenderData.data.lender_details.preapproval_info.zipcode,contactFormRenderData.data.listing.direct_connect.tour_eligible,contactFormRenderData.data.listing.one_advisor,contactFormRenderData.data.listing.supports_unselected_leads,contactFormRenderData.data.opaque_la,contactFormRenderData.data.pixel_id,contactFormRenderData.data.pixel_url,contactFormRenderData.data.premier_agent_preferred_property,contactFormRenderData.data.region_phone_number.areacode,contactFormRenderData.data.region_phone_number.number,contactFormRenderData.data.region_phone_number.prefix,contactFormRenderData.data.request_trace.xpi,contactFormRenderData.data.request_trace.xsi,contactFormRenderData.data.request_trace.xti,contactFormRenderData.data.tcpa,contactFormRenderData.data.text_area.name,contactFormRenderData.data.text_area.value,contactFormRenderData.data.text_fields,contactFormRenderData.data.title,contactFormRenderData.data.tour_config.useFoundation,contactFormRenderData.data.tour_eligible,contactFormRenderData.data.variant,ZoDsFsUpsellTop.display,ZoDsFsUpsellTop.displayCategory,ZoDsFsUpsellTop.displayAttributes.leadType,ZoDsFsUpsellTop.treatment,ZoDsFsUpsellTop.surfaceId,ZoDsFsUpsellTop.placementId,ZoDsFsUpsellTop.reason,onsiteMessage.eventId,onsiteMessage.messages,foreclosureTypes.isBankOwned,foreclosureTypes.isForeclosedNFS,foreclosureTypes.isPreforeclosure,foreclosureTypes.isAnyForeclosure,foreclosureTypes.wasNonRetailAuction,foreclosureTypes.wasForeclosed,foreclosureTypes.wasREO,foreclosureTypes.wasDefault,staticMap.sources,listingSubType.isFSBA,listingSubType.isFSBO,listingSubType.isPending,listingSubType.isNewHome,listingSubType.isForeclosure,listingSubType.isBankOwned,listingSubType.isForAuction,listingSubType.isOpenHouse,listingSubType.isComingSoon,postingContact.name,postingContact.photo,vrModel.vrModelGuid,vrModel.revisionId,thirdPartyVirtualTour.externalUrl,thirdPartyVirtualTour.lightboxUrl,thirdPartyVirtualTour.staticUrl,thirdPartyVirtualTour.providerKey,thirdPartyVirtualTour.approved,topNavJson.topnav.json.logo.text,topNavJson.topnav.json.logo.href,topNavJson.topnav.json.main.sections,topNavJson.topnav.json.agent,topNavJson.topnav.json.marketing.sections,topNavJson.topnav.json.regLogin.sections,topNavJson.topnav.json.help.sections,topNavJson.topnav.json.common.home.text,topNavJson.topnav.json.common.home.href,topNavJson.topnav.json.common.advertise.text,topNavJson.topnav.json.common.advertise.href,topNavJson.topnav.json.common.login.text,topNavJson.topnav.json.common.login.href,topNavJson.topnav.json.common.register.text,topNavJson.topnav.json.common.register.href,topNavJson.core.js,formattedChip.location,selfTour.hasSelfTour

In [ ]:
# features
# phone number
df_fsbo_prop["phone_number"] = df_fsbo_prop.apply(lambda x:
  x["contactFormRenderData.data.agent_module.phone.areacode"] + '-' +
  x["contactFormRenderData.data.agent_module.phone.prefix"] + '-' +
  x["contactFormRenderData.data.agent_module.phone.number"], axis=1)
# full address
df_fsbo_prop["full_address"] = df_fsbo_prop.apply(lambda x:
  x["streetAddress"] + ', ' +
  x["city"] + ', ' +
  x["state"] + ' ' + x["zipcode"], axis=1)

print("The phone number for property address {} is {}".format(
    list(df_fsbo_prop["full_address"])[0],
    list(df_fsbo_prop["phone_number"])[0]))

The phone number for property address 2014 E Broad St, Tampa, FL 33610 is 813-400-7777

### <font color="green">6. Canada Listings</font>
*Coming soon*

# End Notebook