In [ ]:
from fredapi import Fred
import pandas as pd

# Replace with your actual FRED API key
fred = Fred(api_key="ENTER API KEY HERE")

# Pull 30-Year Fixed Rate Mortgage, monthly data
mortgage = fred.get_series(
    "MORTGAGE30US", start_date="2015-01-01", end_date="2025-12-01"
)

# Optional: convert to a DataFrame and reset index
mortgage_df = mortgage.to_frame(name="mortgage_rate")
mortgage_df.index.name = "date"
mortgage_df.reset_index(inplace=True)

print(mortgage_df.head())

        date  mortgage_rate
0 1971-04-02           7.33
1 1971-04-09           7.31
2 1971-04-16           7.31
3 1971-04-23           7.31
4 1971-04-30           7.29

In [10]:

# Keep only data from 2015 onwards
mortgage_df = mortgage_df[mortgage_df["date"] >= "2015-01-01"]
mortgage_df.head()

           date  mortgage_rate
2284 2015-01-08           3.73
2285 2015-01-15           3.66
2286 2015-01-22           3.63
2287 2015-01-29           3.66
2288 2015-02-05           3.59

In [8]:
mortgage_df.tail()

           date  mortgage_rate
2849 2025-11-06           6.22
2850 2025-11-13           6.24
2851 2025-11-20           6.26
2852 2025-11-26           6.23
2853 2025-12-04           6.19

In [6]:
len(mortgage_df)

570

In [ ]:
import requests

url = "https://real-time-real-estate-data.p.rapidapi.com/search"

querystring = {
    "location": "Los Angeles, CA",
    "home_status": "FOR_SALE",
    "sort": "DEFAULT",
    "listing_type": "BY_AGENT",
}

headers = {
    "x-rapidapi-key": "ENTER KEY HERE",
    "x-rapidapi-host": "ENTER KEY HERE",
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'status': 'OK', 'request_id': 'd900b53e-07a4-46ef-bfb7-31235d29513b', 'parameters': {'page': 1, 'home_status': 'FOR_SALE', 'sort': 'DEFAULT', 'listing_type': 'BY_AGENT', 'location': 'Los Angeles, CA'}, 'data': [{'zpid': '20379916', 'homeStatus': 'FOR_SALE', 'detailUrl': 'https://www.zillow.com/homedetails/7818-Truxton-Ave-Los-Angeles-CA-90045/20379916_zpid/', 'address': '7818 Truxton Ave, Los Angeles, CA 90045', 'streetAddress': '7818 Truxton Ave', 'city': 'Los Angeles', 'state': 'CA', 'country': 'USA', 'zipcode': '90045', 'latitude': 33.968838, 'longitude': -118.39258, 'homeType': 'SINGLE_FAMILY', 'price': 1199000, 'currency': 'USD', 'zestimate': 1226700, 'rentZestimate': 5217, 'taxAssessedValue': 1271855, 'lotAreaValue': 6006.924, 'lotAreaUnit': 'sqft', 'bathrooms': 2, 'bedrooms': 3, 'livingArea': 1001, 'daysOnZillow': 5, 'isFeatured': False, 'openHouse': 'Tue. 11:30am-2pm', 'isPreforeclosureAuction': False, 'timeOnZillow': 435956000, 'isNonOwnerOccupied': True, 'isPremierBuilder': False, 'isZillowOwned': False, 'isShowcaseListing': True, 'listingSubType': {'is_FSBA': True, 'is_openHouse': True}, 'palsId': '17327010_25613939', 'id': '20379916', 'rawHomeStatusCd': 'ForSale', 'marketingStatusSimplifiedCd': 'For Sale by Agent', 'imgSrc': 'https://photos.zillowstatic.com/fp/f675a613f54dad219fbb3e8656dd72f2-p_e.jpg', 'hasImage': True, 'statusType': 'FOR_SALE', 'statusText': 'House for sale', 'countryCurrency': '$', 'unformattedPrice': 1199000, 'addressStreet': '7818 Truxton Ave', 'addressCity': 'Los Angeles', 'addressState': 'CA', 'addressZipcode': '90045', 'isUndisclosedAddress': False, 'shouldShowRequestOnPrice': False, 'beds': 3, 'baths': 2, 'area': 1001, 'latLong': {'latitude': 33.968838, 'longitude': -118.39258}, 'flexFieldText': 'Open: Tue 11:30am-2pm (12/9)', 'contentType': 'openHouse', 'hdpData': {'homeInfo': {'zpid': 20379916, 'streetAddress': '7818 Truxton Ave', 'zipcode': '90045', 'city': 'Los Angeles', 'state': 'CA', 'latitude': 33.968838, 'longitude': -118.39258, 'price': 1199000, 'bathrooms': 2, 'bedrooms': 3, 'livingArea': 1001, 'homeType': 'SINGLE_FAMILY', 'homeStatus': 'FOR_SALE', 'daysOnZillow': 5, 'isFeatured': False, 'shouldHighlight': False, 'zestimate': 1226700, 'rentZestimate': 5217, 'listing_sub_type': {'is_FSBA': True, 'is_openHouse': True}, 'openHouse': 'Tue. 11:30am-2pm', 'isUnmappable': False, 'isPreforeclosureAuction': False, 'homeStatusForHDP': 'FOR_SALE', 'priceForHDP': 1199000, 'open_house_info': {'open_house_showing': [{'open_house_start': 1765308600000, 'open_house_end': 1765317600000}, {'open_house_start': 1765395000000, 'open_house_end': 1765402200000}]}, 'timeOnZillow': 435956000, 'isNonOwnerOccupied': True, 'isPremierBuilder': False, 'isZillowOwned': False, 'currency': 'USD', 'country': 'USA', 'taxAssessedValue': 1271855, 'lotAreaValue': 6006.924, 'lotAreaUnit': 'sqft', 'isShowcaseListing': True}}, 'isSaved': False, 'isUserClaimingOwner': False, 'isUserConfirmedClaim': False, 'pgapt': 'ForSale', 'sgapt': 'For Sale (Broker)', 'shouldShowZestimateAsPrice': False, 'has3DModel': True, 'hasVideo': False, 'isHomeRec': False, 'hasAdditionalAttributions': True, 'isFeaturedListing': False, 'list': True, 'relaxed': False, 'info6String': 'Stephanie Younger DRE # 01365696', 'brokerName': 'Compass', 'carouselPhotosComposable': {'baseUrl': 'https://photos.zillowstatic.com/fp/{photoKey}-p_e.jpg', 'communityBaseUrl': None, 'photoData': [{'photoKey': 'f675a613f54dad219fbb3e8656dd72f2'}, {'photoKey': '54fdd0bd159cb6157f37e65180333c28'}, {'photoKey': 'c50dae7f8c3bdeb21ce895d2d9128b70'}, {'photoKey': '4c508e4c645c117fd73bf56b55bbedf2'}, {'photoKey': '944e2dff231c63dd07fcf48c8c468acf'}, {'photoKey': 'b4adaf31cf8d70f7f460c546372511ae'}, {'photoKey': 'b39cdffd70b4af4601df1563c4ab7fcb'}, {'photoKey': '4a928a30c24af0483db0d801572ac0df'}, {'photoKey': '5214526ef45718d235c2aa7623ff9262'}, {'photoKey': '015cca28905cb5e8e62d47803adada00'}, {'photoKey': 'f90410c226e0a63bef5367f3fb4f2c94'}, {'photoKey': 'f7ad7ed4a9b927be0f27692bb0297c92'}, {'photoKey': 'ab39a166556e311407ef83dd4bbfdaee'}, {'photoKey': '28419c330326d3f3b0ceff8348d74782'}, {'photoKey': 'ed9c465ee36f46aec04d569850a605cd'}, {'photoKey': 'dedfeca4a2ebaf481b15d59b74853212'}, {'photoKey': 'be4879b0a46d494008d2ec4b8032fa99'}, {'photoKey': '471fe95c76906aad0ffe34727dacf4bd'}, {'photoKey': 'b5306673239bb201d076773a42edbc70'}, {'photoKey': 'b6a69df566b9c06c908589d56f97182b'}, {'photoKey': '755300feb1f0673e7c8617cf345d6c71'}, {'photoKey': '4b5da4da96879f06822f8797c029c6b8'}], 'communityPhotoData': None, 'isStaticUrls': False}, 'hasOpenHouse': True, 'openHouseStartDate': '2025-12-09T11:30:00', 'openHouseEndDate': '2025-12-09T14:00:00', 'openHouseDescription': 'Open House - 11:30 AM - 2:00 PM', 'isPaidBuilderNewConstruction': False}, {'zpid': '19962131', 'homeStatus': 'FOR_SALE', 'detailUrl': 'https://www.zillow.com/homedetails/15354-Runnymede-St-Van-Nuys-CA-91406/19962131_zpid/', 'address': '15354 Runnymede St, Van Nuys, CA 91406', 'streetAddress': '15354 Runnymede St', 'city': 'Van Nuys', 'state': 'CA', 'country': 'USA', 'zipcode': '91406', 'latitude': 34.205437, 'longitude': -118.46828, 'homeType': 'SINGLE_FAMILY', 'price': 839900, 'currency': 'USD', 'zestimate': 838300, 'rentZestimate': 4677, 'taxAssessedValue': 834360, 'lotAreaValue': 6057, 'lotAreaUnit': 'sqft', 'bathrooms': 2, 'bedrooms': 4, 'livingArea': 1774, 'daysOnZillow': 7, 'isFeatured': False, 'isPreforeclosureAuction': False, 'timeOnZillow': 614249000, 'isNonOwnerOccupied': True, 'isPremierBuilder': False, 'isZillowOwned': False, 'isShowcaseListing': True, 'listingSubType': {'is_FSBA': True}, 'palsId': '3009_SR25269158', 'id': '19962131', 'rawHomeStatusCd': 'ForSale', 'marketingStatusSimplifiedCd': 'For Sale by Agent', 'imgSrc': 'https://photos.zillowstatic.com/fp/f0a248a10438b2099a200970abfe532b-p_e.jpg', 'hasImage': True, 'statusType': 'FOR_SALE', 'statusText': 'House for sale', 'countryCurrency': '$', 'unformattedPrice': 839900, 'addressStreet': '15354 Runnymede St', 'addressCity': 'Van Nuys', 'addressState': 'CA', 'addressZipcode': '91406', 'isUndisclosedAddress': False, 'shouldShowRequestOnPrice': False, 'beds': 4, 'baths': 2, 'area': 1774, 'latLong': {'latitude': 34.205437, 'longitude': -118.46828}, 'flexFieldText': 'Showcase', 'contentType': 'showcase', 'hdpData': {'homeInfo': {'zpid': 19962131, 'streetAddress': '15354 Runnymede St', 'zipcode': '91406', 'city': 'Van Nuys', 'state': 'CA', 'latitude': 34.205437, 'longitude': -118.46828, 'price': 839900, 'bathrooms': 2, 'bedrooms': 4, 'livingArea': 1774, 'homeType': 'SINGLE_FAMILY', 'homeStatus': 'FOR_SALE', 'daysOnZillow': 7, 'isFeatured': False, 'shouldHighlight': False, 'zestimate': 838300, 'rentZestimate': 4677, 'listing_sub_type': {'is_FSBA': True}, 'isUnmappable': False, 'isPreforeclosureAuction': False, 'homeStatusForHDP': 'FOR_SALE', 'priceForHDP': 839900, 'timeOnZillow': 614249000, 'isNonOwnerOccupied': True, 'isPremierBuilder': False, 'isZillowOwned': False, 'currency': 'USD', 'country': 'USA', 'taxAssessedValue': 834360, 'lotAreaValue': 6057, 'lotAreaUnit': 'sqft', 'isShowcaseListing': True}}, 'isSaved': False, 'isUserClaimingOwner': False, 'isUserConfirmedClaim': False, 'pgapt': 'ForSale', 'sgapt': 'For Sale (Broker)', 'shouldShowZestimateAsPrice': False, 'has3DModel': True, 'hasVideo': False, 'isHomeRec': False, 'hasAdditionalAttributions': True, 'isFeaturedListing': False, 'list': True, 'relaxed': False, 'brokerName': 'Berkshire Hathaway HomeServices California Properties', 'carouselPhotosComposable': {'baseUrl': 'https://photos.zillowstatic.com/fp/{photoKey}-p_e.jpg', 'communityBaseUrl': None, 'photoData': [{'photoKey': 'f0a248a10438b2099a200970abfe532b'}, {'photoKey': '1e44ca955e7a852b176c0d410a04e5ad'}, {'photoKey': '53172e99225a3bab64838d310482f904'}, {'photoKey': 'e721aa9d2bdb13a24e290c728e8620ce'}, {'photoKey': '21c4523ceeb44d2df96089816bfb8c92'}, {'photoKey': '8532b732147b14c5339136fd366bec1f'}, {'photoKey': '8b124f925d1a8bcbb4f4260fe5f12e36'}, {'photoKey': '892cebe80e02dc3fa972824a07ba6c5b'}, {'photoKey': 'd1f9c93deecb8e4c7171417e78f2a7e4'}, {'photoKey': 'ea5ee67c195bc0eef3fd09698c1e4e3f'}, {'photoKey': 'efc95f1dfafdf15b30c2c968ac491abc'}, {'photoKey': 'deab3f80be473e6e7316df1c40c6f7c4'}, {'photoKey': '6d8f533a32cf5b3cbee1646a94aaf10a'}, {'photoKey': '0168d3d230e8295525f2a4cc0aedf522'}, {'photoKey': '4df0fc44f47c4c2d7983bdf81b2f3023'}, {'photoKey': '757bdf24a893592f3a460b636329a077'}, {'photoKey': '0831176a0c4ff89d6f5da750ef4cd78c'}, {'photoKey': '7c30b43bde27ff35a336adc3054daf6c'}, {'photoKey': '6baddbeee861124e4d9cdd9d3f33432b'}, {'photoKey': '619633aa2d55c2cca687230fd2598c7b'}, {'photoKey': '04654169ebf6bd0845f4f3cef74ba999'}, {'photoKey': '8c88c9997c09262b9e4b991841ad2429'}, {'photoKey': '1e475683a1b67af45fb8ec16051d77a9'}, {'photoKey': 'e63eaa2848d3806a99e09131c0841449'}, {'photoKey': '967c604a703ad0a948f38192dac784b4'}, {'photoKey': '6f41f31f16b36f85b4015515599df888'}, {'photoKey': '76898940352d8ad676fda1327f0ba8ff'}, {'photoKey': 'ff162be0d5f6a4b6a61ed2259fc342d4'}, {'photoKey': 'efa7bda50570ea4941ceae502770ff4e'}, {'photoKey': 'e9a9d04b6b28289ac8d23b1b343be288'}, {'photoKey': '0231ddfdfe6f0369cd56bd8747f40e94'}, {'photoKey': 'afd6e920d218e227059f5175aaad6cc0'}, {'photoKey': '126080cd13a6077db4b574fe9316a78f'}, {'photoKey': 'd1ad9af8141076eabf7f21431a26ef3f'}, {'photoKey': 'd3b5f3a5b06f993bf96977120affe16b'}, {'photoKey': 'e031d41b9e3c0b596b5b586da55b3b46'}, {'photoKey': 'c712f5e9a6a6b0950aad2cc80446b072'}, {'photoKey': 'deff68f3536e06b3541d76fd0c22d7a9'}, {'photoKey': '08050281b74705a809d722ea47cde938'}, {'photoKey': '17dd75ea36eee309dbf2b1b635d1893a'}, {'photoKey': '02ede1bebbed3666d949e641ac90b7a4'}, {'photoKey': '9347b3751ba060eec16a3fab876b8249'}, {'photoKey': '5eb63ac446e04d330ef1de7cd05754ca'}, {'photoKey': '108c3e85ffd3c6f5c7f6d2d41665e711'}, {'photoKey': 'f2a62bde57d437b55a890ad5b9ef8fd9'}, {'photoKey': '469fe999ff5436a92df692f26d9a5b6c'}, {'photoKey': 'dec08fd43b7ab53517822f0925716470'}, {'photoKey': '6a3e5d8903c8899cf8469cbd30e269ad'}, {'photoKey': 'ec47e1a5d6111a2e0d356bb0aef97013'}, {'photoKey': '73e51e11298c09e6f15477e28359c338'}], 'communityPhotoData': None, 'isStaticUrls': False}, 'isPaidBuilderNewConstruction': False}, {'zpid': '20378925', 'homeStatus': 'FOR_SALE', 'detailUrl': 'https://www.zillow.com/homedetails/5931-Abernathy-Dr-Los-Angeles-CA-90045/20378925_zpid/', 'address': '5931 Abernathy Dr, Los Angeles, CA 90045', 'streetAddress': '5931 Abernathy Dr', 'city': 'Los Angeles', 'state': 'CA', 'country': 'USA', 'zipcode': '90045', 'latitude': 33.971813, 'longitude': -118.38613, 'homeType': 'SINGLE_FAMILY', 'price': 1695000, 'currency': 'USD', 'zestimate': 1685000, 'rentZestimate': 5302, 'taxAssessedValue': 1273448, 'lotAreaValue': 7544.592, 'lotAreaUnit': 'sqft', 'bathrooms': 2, 'bedrooms': 3, 'livingArea': 1550, 'daysOnZillow': 4, 'isFeatured': False, 'openHouse': 'Tue. 11:30am-2pm', 'isPreforeclosureAuction': False, 'timeOnZillow': 355849000, 'isNonOwnerOccupied': True, 'isPremierBuilder': False, 'isZillowOwned': False, 'isShowcaseListing': True, 'listingSubType': {'is_FSBA': True, 'is_openHouse': True}, 'palsId': '17327010_25623299', 'id': '20378925', 'rawHomeStatusCd': 'ForSale', 'marketingStatusSimplifiedCd': 'For Sale by Agent', 'imgSrc': 'https://photos.zillowstatic.com/fp/c5affa839c7204ba7f2dcf86fdcabed7-p_e.jpg', 'hasImage': True, 'statusType': 'FOR_SALE', 'statusText': 'House for sale', 'countryCurrency': '$', 'unformattedPrice': 1695000, 'addressStreet': '5931 Abernathy Dr', 'addressCity': 'Los Angeles', 'addressState': 'CA', 'addressZipcode': '90045', 'isUndisclosedAddress': False, 'shouldShowRequestOnPrice': False, 'beds': 3, 'baths': 2, 'area': 1550, 'latLong': {'latitude': 33.971813, 'longitude': -118.38613}, 'flexFieldText': 'Open: Tue 11:30am-2pm (12/9)', 'contentType': 'openHouse', 'hdpData': {'homeInfo': {'zpid': 20378925, 'streetAddress': '5931 Abernathy Dr', 'zipcode': '90045', 'city': 'Los Angeles', 'state': 'CA', 'latitude': 33.971813, 'longitude': -118.38613, 'price': 1695000, 'bathrooms': 2, 'bedrooms': 3, 'livingArea': 1550, 'homeType': 'SINGLE_FAMILY', 'homeStatus': 'FOR_SALE', 'daysOnZillow': 4, 'isFeatured': False, 'shouldHighlight': False, 'zestimate': 1685000, 'rentZestimate': 5302, 'listing_sub_type': {'is_FSBA': True, 'is_openHouse': True}, 'openHouse': 'Tue. 11:30am-2pm', 'isUnmappable': False, 'isPreforeclosureAuction': False, 'homeStatusForHDP': 'FOR_SALE', 'priceForHDP': 1695000, 'open_house_info': {'open_house_showing': [{'open_house_start': 1765308600000, 'open_house_end': 1765317600000}, {'open_house_start': 1765395000000, 'open_house_end': 1765402200000}, {'open_house_start': 1765407600000, 'open_house_end': 1765418400000}, {'open_house_start': 1765479600000, 'open_house_end': 1765490400000}]}, 'timeOnZillow': 355849000, 'isNonOwnerOccupied': True, 'isPremierBuilder': False, 'isZillowOwned': False, 'currency': 'USD', 'country': 'USA', 'taxAssessedValue': 1273448, 'lotAreaValue': 7544.592, 'lotAreaUnit': 'sqft', 'isShowcaseListing': True}}, 'isSaved': False, 'isUserClaimingOwner': False, 'isUserConfirmedClaim': False, 'pgapt': 'ForSale', 'sgapt': 'For Sale (Broker)', 'shouldShowZestimateAsPrice': False, 'has3DModel': True, 'hasVideo': False, 'isHomeRec': False, 'hasAdditionalAttributions': True, 'isFeaturedListing': False, 'list': True, 'relaxed': False, 'info6String': 'Stephanie Younger DRE # 01365696', 'brokerName': 'Compass', 'carouselPhotosComposable': {'baseUrl': 'https://photos.zillowstatic.com/fp/{photoKey}-p_e.jpg', 'communityBaseUrl': None, 'photoData': [{'photoKey': 'c5affa839c7204ba7f2dcf86fdcabed7'}, {'photoKey': 'ef70d2131a9849aa0f2a05eb1d8ef9bc'}, {'photoKey': 'b70f94f60a724a5b1ae61640b7252561'}, {'photoKey': 'e3ecd52c7d2bfbc10f7677d8382bbe6d'}, {'photoKey': '8c7da079dc4f15a02b1a34b19953af08'}, {'photoKey': 'b27d24ef6dc9e4f42475f8a8b10ecca0'}, {'photoKey': '0f0ad38af71b12c795997e96f10e2fa8'}, {'photoKey': 'bc0675b51115fd2c0a60ff8ea08a3e05'}, {'photoKey': '93ad97cb7af3c4ce5ed537ae39305f50'}, {'photoKey': '8275eca926a2891af8fae410e8d1ce94'}, {'photoKey': 'af2250d382a3107b7048eeb078416aca'}, {'photoKey': '7ca9aadb88c44c65624d9e8cb40817d0'}, {'photoKey': '4b15355b602718ab9cc1ee1824e7b12c'}, {'photoKey': 'b2691c6c20f059203718dc5801072b2b'}, {'photoKey': '1b008bd02be1ccfa295f5395d31f1fe2'}, {'photoKey': '18d6c2e1701c98638eda05e58660d9b3'}, {'photoKey': '1bd8a863fef7708920437cdd2b0a0965'}, {'photoKey': '93c95427ab63c80ed4080cc4b3b45ea5'}, {'photoKey': '5c8c274720f6b416f2b3c9a293bfd774'}, {'photoKey': 'ff495e38f512d5c2e7d01e5b2d3ec90f'}, {'photoKey': '128cbeedf3f6da20b93a03037b5be61c'}, {'photoKey': '94d9cd4f600906bc4af5fdc98f169249'}], 'communityPhotoData': None, 'isStaticUrls': False}, 'hasOpenHouse': True, 'openHouseStartDate': '2025-12-09T11:30:00', 'openHouseEndDate': '2025-12-09T14:00:00', 'openHouseDescription': 'Open House - 11:30 AM - 2:00 PM', 'isPaidBuilderNewConstruction': False}, {'zpid': '20774333', 'homeStatus': 'FOR_SALE', 'detailUrl': 'https://www.zillow.com/homedetails/455-Lorraine-Blvd-Los-Angeles-CA-90020/20774333_zpid/', 'address': '455 Lorraine Blvd, Los Angeles, CA 90020', 'streetAddress': '455 Lorraine Blvd', 'city': 'Los Angeles', 'state': 'CA', 'country': 'USA', 'zipcode': '90020', 'latitude': 34.065678, 'longitude': -118.3204, 'homeType': 'SINGLE_FAMILY', 'price': 12888000, 'priceChange': -2112000, 'currency': 'USD', 'zestimate': 12306800, 'rentZestimate': 8624, 'taxAssessedValue': 13033055, 'lotAreaValue': 0.8261, 'lotAreaUnit': 'acres', 'datePriceChanged': 1724742000000, 'bathrooms': 8, 'bedrooms': 6, 'livingArea': 9329, 'daysOnZillow': 26, 'isFeatured': False, 'openHouse': 'Tue. 11am-1pm', 'priceReduction': '', 'isPreforeclosureAuction': False, 'timeOnZillow': 2246682000, 'isNonOwnerOccupied': True, 'isPremierBuilder': False, 'isZillowOwned': False, 'isShowcaseListing': True, 'listingSubType': {'is_FSBA': True, 'is_openHouse': True}, 'palsId': '17327010_25618441', 'id': '20774333', 'rawHomeStatusCd': 'ForSale', 'marketingStatusSimplifiedCd': 'For Sale by Agent', 'imgSrc': 'https://photos.zillowstatic.com/fp/e99660bc94af95b25c494c14908d2eac-p_e.jpg', 'hasImage': True, 'statusType': 'FOR_SALE', 'statusText': 'House for sale', 'countryCurrency': '$', 'unformattedPrice': 12888000, 'addressStreet': '455 Lorraine Blvd', 'addressCity': 'Los Angeles', 'addressState': 'CA', 'addressZipcode': '90020', 'isUndisclosedAddress': False, 'shouldShowRequestOnPrice': False, 'beds': 6, 'baths': 8, 'area': 9329, 'latLong': {'latitude': 34.065678, 'longitude': -118.3204}, 'flexFieldText': 'Open: Tue 11am-1pm (12/9)', 'contentType': 'openHouse', 'hdpData': {'homeInfo': {'zpid': 20774333, 'streetAddress': '455 Lorraine Blvd', 'zipcode': '90020', 'city': 'Los Angeles', 'state': 'CA', 'latitude': 34.065678, 'longitude': -118.3204, 'price': 12888000, 'datePriceChanged': 1724742000000, 'bathrooms': 8, 'bedrooms': 6, 'livingArea': 9329, 'homeType': 'SINGLE_FAMILY', 'homeStatus': 'FOR_SALE', 'daysOnZillow': 26, 'isFeatured': False, 'shouldHighlight': False, 'zestimate': 12306800, 'rentZestimate': 8624, 'listing_sub_type': {'is_FSBA': True, 'is_openHouse': True}, 'openHouse': 'Tue. 11am-1pm', 'priceReduction': '', 'isUnmappable': False, 'isPreforeclosureAuction': False, 'homeStatusForHDP': 'FOR_SALE', 'priceForHDP': 12888000, 'open_house_info': {'open_house_showing': [{'open_house_start': 1765306800000, 'open_house_end': 1765314000000}]}, 'priceChange': -2112000, 'timeOnZillow': 2246682000, 'isNonOwnerOccupied': True, 'isPremierBuilder': False, 'isZillowOwned': False, 'currency': 'USD', 'country': 'USA', 'taxAssessedValue': 13033055, 'lotAreaValue': 0.8261, 'lotAreaUnit': 'acres', 'isShowcaseListing': True}}, 'isSaved': False, 'isUserClaimingOwner': False, 'isUserConfirmedClaim': False, 'pgapt': 'ForSale', 'sgapt': 'For Sale (Broker)', 'shouldShowZestimateAsPrice': False, 'has3DModel': True, 'hasVideo': False, 'isHomeRec': False, 'hasAdditionalAttributions': True, 'isFeaturedListing': False, 'list': True, 'relaxed': False, 'info6String': 'Shahryar Bastani DRE # 02159470', 'brokerName': "Christie's International Real Estate SoCal", 'carouselPhotosComposable': {'baseUrl': 'https://photos.zillowstatic.com/fp/{photoKey}-p_e.jpg', 'communityBaseUrl': None, 'photoData': [{'photoKey': 'e99660bc94af95b25c494c14908d2eac'}, {'photoKey': '2991f10b92c8d8cb0396f7a031547321'}, {'photoKey': '6b2b623bce6040ee8d60381e85c7c4f7'}, {'photoKey': 'fcb223424fe62840e7358d2a18c832b4'}, {'photoKey': '26fc09e994c5f745f1e1441c58d18247'}, {'photoKey': '48eeec3eb03cba030c0a1904d493f560'}, {'photoKey': 'af047d0129ad106cf454fd26371503de'}, {'photoKey': 'f0852961d9f22153d2b40f55bb7a642d'}, {'photoKey': '6f1ea5801ba45cf07e0ce69f1f179cb7'}, {'photoKey': 'c692c98da5223a16cb683cc9ebbd6336'}, {'photoKey': '39fb30279e8ab2daacf455b2ebc3c3fe'}, {'photoKey': '9e9a05660e065356036a9c4f0e32e0a9'}, {'photoKey': 'c32c7f627c3e7926d61e8a82e65115fb'}, {'photoKey': '1e3cca805992fa2bf6d0260d5110e5de'}, {'photoKey': '5d974c8cef55d83ea0878c1d30033ea1'}, {'photoKey': '46f12d772d2852140d4d730a9529ced9'}, {'photoKey': '1c1d2f76e06823b27c4869ee9981f645'}, {'photoKey': '5885bbb33d0062cc956ed268d271740c'}, {'photoKey': '3df030baa1cce27d9af658a3007d7bee'}, {'photoKey': '3427126bc25a7a34546ee5071a37e5e5'}, {'photoKey': '8acf85e0af62eeda7d1afcfb370d3255'}, {'photoKey': '53196e221ec678c76e0f9e590fe0bb70'}, {'photoKey': '181b6d44e06e52522c6be2b31f6d1f5f'}, {'photoKey': '0af56457b811f7d42fb396ac2ad5ae9a'}, {'photoKey': 'd65fdd906a57398f93273e61b1766942'}, {'photoKey': '7da2935d2212c8f3c8d86c666826f68b'}, {'photoKey': '05ead58fd96d15a320d4d32e7a471675'}, {'photoKey': 'ba433279a941f1677a88a2b819809af4'}, {'photoKey': '88b029b097ae2f93bccb56eddce883bc'}, {'photoKey': '07096be43ae48792674a3305b03206b1'}, {'photoKey': 'a3efab29152892f7be6400d2f662c67a'}, {'photoKey': '211aae38f3db1f16ef6c21a78b458a83'}, {'photoKey': '23cce7f9b0fcfc84cb4ae68c0100d851'}, {'photoKey': 'db97aee64c7130a1248465c33d2e6e4b'}, {'photoKey'

In [15]:
len(response.json()['data'])

41